type SupabaseConfig={url:string;key:string};
function getConfig():SupabaseConfig{const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("SUPABASE_NOT_CONFIGURED");return{url,key};}
function headers(key:string,prefer?:string){return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})};}
export type Cabin={id:string;name:string;leader_registration_id:string|null;capacity:number|null;notes:string|null;leader?:{nombre:string;apellido:string}|null};
export type Team={id:string;name:string;color_name:string;color_hex:string;is_active:boolean;points:number};
export type PointMovement={id:string;team_id:string;points:number;reason:string|null;created_at:string};
export async function listCabins():Promise<Cabin[]>{const{url,key}=getConfig();const r=await fetch(`${url}/rest/v1/cabins?select=id,name,leader_registration_id,capacity,notes,leader:registrations!cabins_leader_registration_id_fkey(nombre,apellido)&order=created_at.asc`,{headers:headers(key),cache:"no-store"});if(!r.ok)throw new Error("CABINS_READ_FAILED");return r.json();}
export async function createCabin(input:{name:string;leaderId?:string;capacity?:number|null;notes?:string}){const{url,key}=getConfig();const r=await fetch(`${url}/rest/v1/cabins`,{method:"POST",headers:headers(key,"return=minimal"),body:JSON.stringify({name:input.name,leader_registration_id:input.leaderId||null,capacity:input.capacity||null,notes:input.notes||null})});if(!r.ok)throw new Error("CABIN_CREATE_FAILED");}
export async function deleteCabin(id:string){const{url,key}=getConfig();const r=await fetch(`${url}/rest/v1/cabins?id=eq.${encodeURIComponent(id)}`,{method:"DELETE",headers:headers(key,"return=minimal")});if(!r.ok)throw new Error("CABIN_DELETE_FAILED");}
export async function listTeams():Promise<Team[]>{const{url,key}=getConfig();const [teamsRes,pointsRes]=await Promise.all([fetch(`${url}/rest/v1/teams?select=*&order=created_at.asc`,{headers:headers(key),cache:"no-store"}),fetch(`${url}/rest/v1/team_point_movements?select=team_id,points`,{headers:headers(key),cache:"no-store"})]);if(!teamsRes.ok||!pointsRes.ok)throw new Error("TEAMS_READ_FAILED");const teams=await teamsRes.json() as any[];const movements=await pointsRes.json() as any[];const totals=new Map<string,number>();for(const m of movements)totals.set(m.team_id,(totals.get(m.team_id)||0)+Number(m.points||0));return teams.map(t=>({...t,points:totals.get(t.id)||0}));}
export async function createTeam(input:{name:string;colorName:string;colorHex:string}){const{url,key}=getConfig();const r=await fetch(`${url}/rest/v1/teams`,{method:"POST",headers:headers(key,"return=minimal"),body:JSON.stringify({name:input.name,color_name:input.colorName||input.name,color_hex:input.colorHex||"#0E3B31"})});if(!r.ok)throw new Error("TEAM_CREATE_FAILED");}
export async function deleteTeam(id:string){const{url,key}=getConfig();const r=await fetch(`${url}/rest/v1/teams?id=eq.${encodeURIComponent(id)}`,{method:"DELETE",headers:headers(key,"return=minimal")});if(!r.ok)throw new Error("TEAM_DELETE_FAILED");}
export async function addTeamPoints(teamId:string,points:number,reason?:string){const{url,key}=getConfig();const r=await fetch(`${url}/rest/v1/team_point_movements`,{method:"POST",headers:headers(key,"return=minimal"),body:JSON.stringify({team_id:teamId,points,reason:reason||null})});if(!r.ok)throw new Error("POINTS_SAVE_FAILED");}
export async function listPointMovements(limit=30):Promise<PointMovement[]>{const{url,key}=getConfig();const r=await fetch(`${url}/rest/v1/team_point_movements?select=*&order=created_at.desc&limit=${limit}`,{headers:headers(key),cache:"no-store"});if(!r.ok)throw new Error("POINTS_READ_FAILED");return r.json();}
