export type CampRule={id:number;title:string;description:string;sortOrder:number;isActive:boolean};
export type CampRulesSettings={title:string;subtitle:string;pageEnabled:boolean;showInRegistration:boolean};
const defaults:CampRulesSettings={title:'Reglamento de Gracia Camp',subtitle:'Estas normas nos ayudan a convivir, cuidarnos y aprovechar al máximo el campamento.',pageEnabled:true,showInRegistration:true};
function cfg(){const url=process.env.SUPABASE_URL?.replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('SUPABASE_NOT_CONFIGURED');return{url,key}}
const clean=(value:unknown,max:number)=>String(value??'').replace(/[<>]/g,'').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,max);
async function rest(path:string,init:RequestInit={}){const{url,key}=cfg();return fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(init.headers||{})},cache:'no-store'})}
export async function getCampRulesSettings():Promise<CampRulesSettings>{try{const r=await rest('camp_rules_settings?id=eq.1&select=*');if(!r.ok)return defaults;const[x]=await r.json();return x?{title:x.title,subtitle:x.subtitle,pageEnabled:x.page_enabled,showInRegistration:x.show_in_registration}:defaults}catch{return defaults}}
export async function getCampRules(activeOnly=false):Promise<CampRule[]>{try{const filter=activeOnly?'&is_active=eq.true':'';const r=await rest(`camp_rules?select=*&order=sort_order.asc,id.asc${filter}`);if(!r.ok)return[];return(await r.json()).map((x:any)=>({id:x.id,title:x.title,description:x.description,sortOrder:x.sort_order,isActive:x.is_active}))}catch{return[]}}
export async function saveCampRulesSettings(input:Partial<CampRulesSettings>){const body={title:clean(input.title,120)||defaults.title,subtitle:clean(input.subtitle,500)||defaults.subtitle,page_enabled:Boolean(input.pageEnabled),show_in_registration:Boolean(input.showInRegistration),updated_at:new Date().toISOString()};const r=await rest('camp_rules_settings?id=eq.1',{method:'PATCH',body:JSON.stringify(body),headers:{Prefer:'return=minimal'}});if(!r.ok)throw new Error('RULE_SETTINGS_SAVE_FAILED')}
export async function createCampRule(title:unknown,description:unknown){const rules=await getCampRules();const body={title:clean(title,120),description:clean(description,1000),sort_order:rules.length?Math.max(...rules.map(x=>x.sortOrder))+1:1,is_active:true};if(!body.title||!body.description)throw new Error('RULE_FIELDS_REQUIRED');const r=await rest('camp_rules',{method:'POST',body:JSON.stringify(body),headers:{Prefer:'return=minimal'}});if(!r.ok)throw new Error('RULE_CREATE_FAILED')}
export async function updateCampRule(id:number,title:unknown,description:unknown){const body={title:clean(title,120),description:clean(description,1000),updated_at:new Date().toISOString()};if(!body.title||!body.description)throw new Error('RULE_FIELDS_REQUIRED');const r=await rest(`camp_rules?id=eq.${id}`,{method:'PATCH',body:JSON.stringify(body),headers:{Prefer:'return=minimal'}});if(!r.ok)throw new Error('RULE_UPDATE_FAILED')}
export async function toggleCampRule(id:number,isActive:boolean){const r=await rest(`camp_rules?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({is_active:isActive,updated_at:new Date().toISOString()}),headers:{Prefer:'return=minimal'}});if(!r.ok)throw new Error('RULE_TOGGLE_FAILED')}
export async function deleteCampRule(id:number){const r=await rest(`camp_rules?id=eq.${id}`,{method:'DELETE'});if(!r.ok)throw new Error('RULE_DELETE_FAILED')}
export async function moveCampRule(id:number,direction:'up'|'down'){const rules=await getCampRules();const index=rules.findIndex(x=>x.id===id);const target=direction==='up'?index-1:index+1;if(index<0||target<0||target>=rules.length)return;const a=rules[index],b=rules[target];await Promise.all([rest(`camp_rules?id=eq.${a.id}`,{method:'PATCH',body:JSON.stringify({sort_order:b.sortOrder,updated_at:new Date().toISOString()})}),rest(`camp_rules?id=eq.${b.id}`,{method:'PATCH',body:JSON.stringify({sort_order:a.sortOrder,updated_at:new Date().toISOString()})})])}
