import { publicAssetUrl, uploadSiteAsset } from '@/lib/site-settings';

export type PreacherSettings={sectionEnabled:boolean;eyebrow:string;name:string;role:string;topic:string;description:string;dayLabel:string;church:string;cityCountry:string;photoPath:string;bannerDesktopPath:string;bannerMobilePath:string;showBanner:boolean;showProfileCard:boolean;ctaEnabled:boolean;ctaText:string;ctaHref:string;profilePageEnabled:boolean;profileTitle:string;biography:string;sermon1Title:string;sermon1Url:string;sermon2Title:string;sermon2Url:string;sermon3Title:string;sermon3Url:string};
const defaults:PreacherSettings={sectionEnabled:true,eyebrow:'Predicador invitado',name:'Pastor Homero González',role:'Pastor',topic:'El evangelio en el foso de los peligros de la cultura',description:'Una exposición centrada en el evangelio para pensar cómo vivir una fe firme en medio de los desafíos de nuestra cultura.',dayLabel:'Gracia Camp 2026',church:'',cityCountry:'',photoPath:'',bannerDesktopPath:'',bannerMobilePath:'',showBanner:true,showProfileCard:true,ctaEnabled:true,ctaText:'Conocer al predicador',ctaHref:'/predicador',profilePageEnabled:true,profileTitle:'Conocé al predicador',biography:'',sermon1Title:'',sermon1Url:'',sermon2Title:'',sermon2Url:'',sermon3Title:'',sermon3Url:''};
function cfg(){const url=process.env.SUPABASE_URL?.replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('SUPABASE_NOT_CONFIGURED');return{url,key}}
export async function getPreacherSettings():Promise<PreacherSettings>{try{const{url,key}=cfg();const r=await fetch(`${url}/rest/v1/preacher_settings?id=eq.1&select=*`,{headers:{apikey:key,Authorization:`Bearer ${key}`},cache:'no-store'});if(!r.ok)return defaults;const[x]=await r.json();if(!x)return defaults;return{sectionEnabled:x.section_enabled,eyebrow:x.eyebrow,name:x.name,role:x.role,topic:x.topic,description:x.description,dayLabel:x.day_label,church:x.church||'',cityCountry:x.city_country||'',photoPath:x.photo_path||'',bannerDesktopPath:x.banner_desktop_path||'',bannerMobilePath:x.banner_mobile_path||'',showBanner:x.show_banner,showProfileCard:x.show_profile_card,ctaEnabled:x.cta_enabled,ctaText:x.cta_text,ctaHref:x.cta_href,profilePageEnabled:x.profile_page_enabled??true,profileTitle:x.profile_title||'Conocé al predicador',biography:x.biography||'',sermon1Title:x.sermon_1_title||'',sermon1Url:x.sermon_1_url||'',sermon2Title:x.sermon_2_title||'',sermon2Url:x.sermon_2_url||'',sermon3Title:x.sermon_3_title||'',sermon3Url:x.sermon_3_url||''}}catch{return defaults}}
export async function savePreacher(data:Record<string,unknown>){const{url,key}=cfg();const r=await fetch(`${url}/rest/v1/preacher_settings?id=eq.1`,{method:'PATCH',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({...data,updated_at:new Date().toISOString()}),cache:'no-store'});if(!r.ok)throw new Error('PREACHER_SAVE_FAILED')}
export async function uploadPreacherImage(file:File,prefix:string){return uploadSiteAsset(file,`preacher-${prefix}`)}
export function preacherImageUrl(path:string,fallback=''){return path?publicAssetUrl(path):fallback}
