import {publicAssetUrl,uploadSiteAsset} from '@/lib/site-settings';
export type RegistrationSettings={pageEyebrow:string;pageTitle:string;pageDescription:string;campPrice:number;shirtPrice:number;shirtXlPrice:number;capPrice:number;shirtSizes:string[];shirtColors:{id:string;label:string;hex:string}[];capColors:{id:string;label:string;hex:string}[];bannerEnabled:boolean;bannerDesktopPath:string;bannerMobilePath:string;bannerAlt:string;sectionTitles:string[];shirtHeading:string;capHeading:string;paymentHeading:string;paymentDescription:string;submitButtonText:string};
const colors=[{id:'blanco',label:'Blanco',hex:'#FFFFFF'},{id:'verde',label:'Verde',hex:'#142B23'},{id:'azul',label:'Azul',hex:'#09193A'}];
export const registrationDefaults:RegistrationSettings={pageEyebrow:'Ministerio de Jóvenes CBG',pageTitle:'Registro Campamento 2026',pageDescription:'Completá tus datos y confirmá tu inscripción con la transferencia.',campPrice:450000,shirtPrice:100000,shirtXlPrice:120000,capPrice:30000,shirtSizes:['S','M','L','XL','XXL','XXXL'],shirtColors:colors,capColors:colors,bannerEnabled:true,bannerDesktopPath:'',bannerMobilePath:'',bannerAlt:'Merch oficial Gracia Camp: remeras y gorras',sectionTitles:['Datos personales','Información adicional','Responsable','Salud','Emergencia','Merch oficial','Pago'],shirtHeading:'Elegí tu remera Gracia Camp',capHeading:'¿Querés agregar la gorra?',paymentHeading:'Revisá el total antes de transferir',paymentDescription:'La inscripción solo se completa cuando adjuntás el comprobante.',submitButtonText:'Enviar registro'};
function cfg(){const url=process.env.SUPABASE_URL?.replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('SUPABASE_NOT_CONFIGURED');return{url,key};}
export async function getRegistrationSettings():Promise<RegistrationSettings>{try{const{url,key}=cfg();const r=await fetch(`${url}/rest/v1/registration_settings?id=eq.1&select=*`,{headers:{apikey:key,Authorization:`Bearer ${key}`},cache:'no-store'});if(!r.ok)return registrationDefaults;const[x]=await r.json();if(!x)return registrationDefaults;return{pageEyebrow:x.page_eyebrow,pageTitle:x.page_title,pageDescription:x.page_description,campPrice:x.camp_price,shirtPrice:x.shirt_price,shirtXlPrice:x.shirt_xl_price,capPrice:x.cap_price,shirtSizes:x.shirt_sizes||registrationDefaults.shirtSizes,shirtColors:x.shirt_colors||colors,capColors:x.cap_colors||colors,bannerEnabled:x.banner_enabled,bannerDesktopPath:x.banner_desktop_path||'',bannerMobilePath:x.banner_mobile_path||'',bannerAlt:x.banner_alt,sectionTitles:[x.section_01_title,x.section_02_title,x.section_03_title,x.section_04_title,x.section_05_title,x.section_06_title,x.section_07_title],shirtHeading:x.shirt_heading,capHeading:x.cap_heading,paymentHeading:x.payment_heading,paymentDescription:x.payment_description,submitButtonText:x.submit_button_text};}catch{return registrationDefaults;}}
export async function saveRegistrationSettings(data:Record<string,unknown>){const{url,key}=cfg();const r=await fetch(`${url}/rest/v1/registration_settings?id=eq.1`,{method:'PATCH',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({...data,updated_at:new Date().toISOString()}),cache:'no-store'});if(!r.ok)throw new Error('REGISTRATION_SETTINGS_SAVE_FAILED');}
export async function uploadRegistrationImage(file:File,prefix:string){return uploadSiteAsset(file,`registration-${prefix}`)}
export function registrationImageUrl(path:string,fallback:string){return path?publicAssetUrl(path):fallback;}
