export type SiteSettings = {
  siteName:string; siteTagline:string; showLogo:boolean; showSiteText:boolean; logoPath:string;
  logoSizeMobile:number; logoSizeTablet:number; logoSizeDesktop:number; stickyHeader:boolean;
  showCountdown:boolean; countdownLabel:string; showCta:boolean; ctaText:string; ctaHref:string;
  nav:Record<string,boolean>; showBanner:boolean; bannerDesktopPath:string; bannerMobilePath:string;
  bannerHref:string; bannerAlt:string; bannerMaxHeightDesktop:number; bannerMaxHeightMobile:number;
  showMusic:boolean; musicPath:string; musicTitle:string; musicAutoplay:boolean; musicLoop:boolean; musicVolume:number;
};

const defaults: SiteSettings = {siteName:'Jóvenes CBG',siteTagline:'Crecer · Compartir · Servir',showLogo:true,showSiteText:true,logoPath:'',logoSizeMobile:56,logoSizeTablet:64,logoSizeDesktop:72,stickyHeader:true,showCountdown:true,countdownLabel:'Gracia Camp',showCta:true,ctaText:'Inscribirme',ctaHref:'/registro',nav:{inicio:true,nosotros:true,actividades:true,eventos:true,galeria:true,campamento:true,contacto:true},showBanner:false,bannerDesktopPath:'',bannerMobilePath:'',bannerHref:'',bannerAlt:'Banner promocional',bannerMaxHeightDesktop:260,bannerMaxHeightMobile:220,showMusic:false,musicPath:'',musicTitle:'Música Gracia Camp',musicAutoplay:true,musicLoop:true,musicVolume:35};

function config(){const url=process.env.SUPABASE_URL?.replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('SUPABASE_NOT_CONFIGURED');return{url,key};}
function headers(key:string,contentType='application/json'){return{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':contentType};}
export function publicAssetUrl(path:string){if(!path)return '';const {url}=config();return `${url}/storage/v1/object/public/site-assets/${path}`;}
export async function getSiteSettings():Promise<SiteSettings>{try{const {url,key}=config();const r=await fetch(`${url}/rest/v1/site_settings?id=eq.1&select=*`,{headers:headers(key),cache:'no-store'});if(!r.ok)return defaults;const [x]=await r.json();if(!x)return defaults;return{siteName:x.site_name,siteTagline:x.site_tagline,showLogo:x.show_logo,showSiteText:x.show_site_text,logoPath:x.logo_path||'',logoSizeMobile:x.logo_size_mobile,logoSizeTablet:x.logo_size_tablet,logoSizeDesktop:x.logo_size_desktop,stickyHeader:x.sticky_header,showCountdown:x.show_countdown,countdownLabel:x.countdown_label,showCta:x.show_cta,ctaText:x.cta_text,ctaHref:x.cta_href,nav:{inicio:x.show_nav_inicio,nosotros:x.show_nav_nosotros,actividades:x.show_nav_actividades,eventos:x.show_nav_eventos,galeria:x.show_nav_galeria,campamento:x.show_nav_campamento,contacto:x.show_nav_contacto},showBanner:x.show_banner,bannerDesktopPath:x.banner_desktop_path||'',bannerMobilePath:x.banner_mobile_path||'',bannerHref:x.banner_href||'',bannerAlt:x.banner_alt,bannerMaxHeightDesktop:x.banner_max_height_desktop,bannerMaxHeightMobile:x.banner_max_height_mobile,showMusic:x.show_music??false,musicPath:x.music_path||'',musicTitle:x.music_title||'Música Gracia Camp',musicAutoplay:x.music_autoplay??true,musicLoop:x.music_loop??true,musicVolume:x.music_volume??35};}catch{return defaults;}}
export async function uploadSiteAsset(file:File,prefix:string){const {url,key}=config();let ext='jpg';if(file.type==='image/png')ext='png';else if(file.type==='image/webp')ext='webp';else if(file.type==='audio/mpeg')ext='mp3';else if(file.type==='audio/mp4')ext='m4a';else if(file.type==='audio/aac')ext='aac';else if(file.type==='audio/ogg')ext='ogg';else if(file.type==='audio/wav')ext='wav';const path=`${prefix}-${Date.now()}.${ext}`;const r=await fetch(`${url}/storage/v1/object/site-assets/${path}`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':file.type,'x-upsert':'false'},body:await file.arrayBuffer(),cache:'no-store'});if(!r.ok)throw new Error('ASSET_UPLOAD_FAILED');return path;}
export async function updateSiteSettings(data:Record<string,unknown>){const {url,key}=config();const r=await fetch(`${url}/rest/v1/site_settings?id=eq.1`,{method:'PATCH',headers:{...headers(key),Prefer:'return=minimal'},body:JSON.stringify({...data,updated_at:new Date().toISOString()}),cache:'no-store'});if(!r.ok)throw new Error('SETTINGS_SAVE_FAILED');}
