import Image from "next/image";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ButtonLink, Container, Eyebrow } from "@/components/ui/design";

const values=[["01","Cristo al centro","Queremos que cada actividad, decisión y relación apunte a Cristo."],["02","Palabra","Conocer la Biblia, hacer preguntas y aprender a vivirla de manera práctica."],["03","Comunidad","Construir amistades sanas donde podamos acompañarnos y crecer juntos."],["04","Servicio","Entender nuestros dones como una oportunidad para servir a Dios y a otros."]];

export default function NosotrosPage(){return <div className="min-h-screen bg-brand-warmWhite text-brand-ink"><Header/><main>
<section className="bg-brand-forestDark py-16 text-white sm:py-24 lg:py-28"><Container><Eyebrow className="text-brand-gold">Somos Ministerio de Jóvenes CBG</Eyebrow><h1 className="mt-5 max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.045em] sm:text-6xl lg:text-7xl">Un lugar para pertenecer, crecer y vivir una fe propia.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70 sm:text-xl">Acompañamos a jóvenes que quieren conocer más a Cristo, construir relaciones con propósito y llevar su fe a la vida real.</p></Container></section>
<section className="py-16 sm:py-20 lg:py-24"><Container className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><Eyebrow>Nuestra esencia</Eyebrow><h2 className="mt-4 text-4xl font-semibold leading-[1.04] tracking-[-.035em] text-brand-forest sm:text-5xl">Más que reuniones. Una comunidad para caminar juntos.</h2><p className="mt-6 text-lg leading-8 text-brand-muted">Creamos espacios de enseñanza bíblica, conversación, amistad, servicio y experiencias donde cada joven pueda preguntar, descubrir y crecer sin tener que aparentar.</p><ButtonLink href="/actividades" className="mt-8">Ver lo que hacemos →</ButtonLink></div><div className="relative min-h-[380px] overflow-hidden rounded-[2.2rem] sm:min-h-[520px]"><Image src="/bienvenida-bg..jpg" alt="Jóvenes del Ministerio CBG compartiendo juntos" fill sizes="(min-width:1024px)55vw,100vw" className="object-cover"/><div className="absolute inset-x-5 bottom-5 rounded-2xl bg-brand-forestDark/85 p-5 text-white backdrop-blur-sm sm:inset-x-7 sm:bottom-7"><p className="text-sm font-semibold text-brand-gold">Crecer · Compartir · Servir</p><p className="mt-2 text-lg">Queremos que nadie tenga que caminar solo.</p></div></div></Container></section>
<section className="bg-brand-cream py-16 sm:py-20 lg:py-24"><Container><div className="max-w-2xl"><Eyebrow>Lo que nos guía</Eyebrow><h2 className="mt-4 text-4xl font-semibold tracking-[-.035em] text-brand-forest sm:text-5xl">Cuatro ideas simples. Un mismo propósito.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2">{values.map(([n,title,text])=><article key={title} className="rounded-[2rem] border border-brand-border bg-white p-7 sm:p-8"><span className="text-sm font-semibold text-brand-gold">{n}</span><h3 className="mt-8 text-2xl font-semibold text-brand-forest sm:text-3xl">{title}</h3><p className="mt-3 max-w-xl text-base leading-7 text-brand-muted">{text}</p></article>)}</div></Container></section>
<section className="bg-brand-forest py-14 text-white"><Container className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-brand-sageSoft">¿Querés conocernos en persona?</p><h2 className="mt-2 text-3xl font-semibold">Hay un lugar para vos.</h2></div><ButtonLink href="/registro" variant="light" className="min-h-12 px-7">Quiero participar</ButtonLink></Container></section>
</main><Footer/></div>}
