"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Header from "@/components/Header";

const fmt=(n:number)=>`Gs. ${n.toLocaleString("es-PY")}`;
const colors=[["blanco","Blanco"],["negro","Negro"],["gris","Gris"],["azul","Azul"]] as const;

export default function ReservarMerchPage(){
 const[shirt,setShirt]=useState(false),[size,setSize]=useState("M"),[shirtColor,setShirtColor]=useState("negro"),[cap,setCap]=useState(false),[capColor,setCapColor]=useState("negro");
 const[payment,setPayment]=useState({bankName:"",accountHolder:"",accountNumber:"",documentNumber:""}); const[videoUrl,setVideoUrl]=useState(""); const[error,setError]=useState(""),[sending,setSending]=useState(false),[done,setDone]=useState(false);
 useEffect(()=>{fetch("/api/payment-settings").then(r=>r.json()).then(setPayment).catch(()=>{});fetch("/api/merch",{cache:"no-store"}).then(r=>r.json()).then(d=>setVideoUrl(d.videoUrl||"")).catch(()=>{});},[]);
 const shirtPrice=shirt?(["XL","XXL","XXXL"].includes(size)?120000:100000):0; const total=useMemo(()=>shirtPrice+(cap?30000:0),[shirtPrice,cap]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");if(!shirt&&!cap){setError("Elegí al menos una remera o una gorra.");return;}setSending(true);const fd=new FormData(e.currentTarget);fd.set("deseaRemera",shirt?"si":"no");fd.set("talleRemera",size);fd.set("colorRemera",shirtColor);fd.set("deseaGorra",cap?"si":"no");fd.set("colorGorra",capColor);const r=await fetch("/api/reservar-merch",{method:"POST",body:fd});const d=await r.json().catch(()=>({}));setSending(false);if(!r.ok){setError(d.error||"No pudimos enviar tu solicitud.");return;}setDone(true);}
 if(done)return <div className="min-h-screen bg-brand-warmWhite"><Header/><main className="mx-auto max-w-3xl px-5 py-20 text-center"><p className="text-xs font-bold uppercase tracking-[.25em] text-brand-gold">Reserva recibida</p><h1 className="mt-4 text-5xl font-black text-brand-forest">¡Tu merch ya está reservado!</h1><p className="mx-auto mt-5 max-w-xl text-brand-muted">Recibimos tu solicitud y comprobante. El equipo de organización verificará el pago.</p><Link href="/campamento?skipPreview=1" className="mt-8 inline-flex rounded-full bg-brand-forest px-7 py-3.5 font-semibold text-white">Volver al campamento</Link></main></div>;
 return <div className="min-h-screen bg-brand-warmWhite text-brand-ink"><Header/><main className="mx-auto max-w-5xl px-5 py-12 sm:py-16"><div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><aside><p className="text-xs font-bold uppercase tracking-[.25em] text-brand-gold">Merch oficial</p><h1 className="mt-3 text-4xl font-black leading-tight text-brand-forest sm:text-5xl">Reservá tu remera y gorra de Gracia Camp</h1><p className="mt-4 leading-7 text-brand-muted">Elegí tus prendas, transferí el total y adjuntá tu comprobante. Esta reserva es independiente de la inscripción al campamento.</p><div className="mt-7 flex justify-center lg:justify-start">{videoUrl?<video key={videoUrl} src={videoUrl} autoPlay muted loop playsInline controls preload="auto" className="aspect-[9/16] h-auto w-full max-w-[360px] rounded-3xl border border-brand-border bg-black object-contain shadow-sm" aria-label="Video promocional del merch oficial de Gracia Camp"/>:<div className="aspect-[9/16] w-full max-w-[360px] rounded-3xl border border-brand-border bg-brand-cream shadow-sm"/>}</div></aside><form onSubmit={submit} className="space-y-5 rounded-3xl border border-brand-border bg-white p-5 sm:p-7"><div className="grid gap-4 sm:grid-cols-2"><Field name="nombre" label="Nombre"/><Field name="apellido" label="Apellido"/><Field name="telefono" label="Número de teléfono"/></div>
 <Choice title="Remera oficial" active={shirt} onChange={setShirt} price="S, M y L: Gs. 100.000 · Desde XL: Gs. 120.000">{shirt?<div className="mt-4 grid gap-3 sm:grid-cols-2"><Select label="Talle" value={size} onChange={setSize} options={["S","M","L","XL","XXL","XXXL"]}/><Select label="Color" value={shirtColor} onChange={setShirtColor} options={colors}/></div>:null}</Choice>
 <Choice title="Gorra oficial" active={cap} onChange={setCap} price="Precio único: Gs. 30.000">{cap?<div className="mt-4"><Select label="Color" value={capColor} onChange={setCapColor} options={colors}/></div>:null}</Choice>
 <section className="rounded-2xl bg-brand-cream p-5"><div className="flex items-center justify-between"><span className="font-semibold text-brand-forest">Total a transferir</span><strong className="text-2xl text-brand-forest">{fmt(total)}</strong></div>{payment.bankName?<div className="mt-5 grid gap-2 text-sm text-brand-muted"><p><b className="text-brand-forest">Banco:</b> {payment.bankName}</p><p><b className="text-brand-forest">Titular:</b> {payment.accountHolder}</p><p><b className="text-brand-forest">Cuenta / Alias:</b> {payment.accountNumber}</p>{payment.documentNumber?<p><b className="text-brand-forest">CI / RUC:</b> {payment.documentNumber}</p>:null}</div>:null}</section>
 <label className="block"><span className="text-sm font-semibold text-brand-forest">Adjuntar comprobante de pago *</span><input name="comprobante" required type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="mt-2 block w-full rounded-xl border border-brand-border p-3 text-sm"/></label>{error?<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}<button disabled={sending||total===0} className="w-full rounded-full bg-brand-forest px-7 py-4 font-bold text-white disabled:opacity-40">{sending?"Enviando...":"Enviar solicitud de reserva"}</button></form></div></main></div>;
}
function Field({name,label}:{name:string;label:string}){return <label><span className="mb-2 block text-sm font-semibold text-brand-forest">{label} *</span><input name={name} required className="min-h-12 w-full rounded-xl border border-brand-border bg-brand-warmWhite px-4 text-brand-forest placeholder:text-brand-muted/60 outline-none transition focus:border-brand-gold focus:bg-white focus:ring-2 focus:ring-brand-gold/20"/></label>}
function Choice({title,active,onChange,price,children}:{title:string;active:boolean;onChange:(v:boolean)=>void;price:string;children:React.ReactNode}){return <section className="rounded-2xl border border-brand-border p-5"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold text-brand-forest">{title}</h2><p className="mt-1 text-sm text-brand-muted">{price}</p></div><button type="button" onClick={()=>onChange(!active)} className={`rounded-full px-4 py-2 text-sm font-bold ${active?"bg-brand-forest text-white":"bg-brand-cream text-brand-forest"}`}>{active?"Agregado":"Agregar"}</button></div>{children}</section>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:readonly (string|readonly [string,string])[]}){return <label><span className="mb-2 block text-sm font-semibold text-brand-forest">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="min-h-12 w-full rounded-xl border border-brand-border bg-white px-4">{options.map(o=>{const pair=Array.isArray(o)?o:[o,o];return <option key={String(pair[0])} value={String(pair[0])}>{String(pair[1])}</option>})}</select></label>}
