"use client";

import { FormEvent, useState } from "react";

type Props = { enabled:boolean; eyebrow:string; title:string; description:string; sourceType:"youtube"|"upload"; youtubeUrl:string; videoUrl:string; autoplay:boolean; soundEnabled:boolean; loop:boolean; saved?:boolean };

const inputClass="min-h-12 w-full rounded-xl border border-[#c9bea9] bg-white px-4 text-[#0b3b30] placeholder:text-[#807869] focus:border-[#0b4a3b] focus:outline-none focus:ring-2 focus:ring-[#0b4a3b]/15";
const ALLOWED_TYPES=["video/mp4","video/webm","video/quicktime","video/mov","video/x-quicktime"];

export default function VideoOfficialForm(props:Props){
 const[status,setStatus]=useState(""); const[uploading,setUploading]=useState(false);
 async function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const formData=new FormData(form);const file=formData.get("video_file");try{setStatus("");setUploading(true);if(file instanceof File&&file.size>0){const isMov=file.name.toLowerCase().endsWith(".mov");if(!ALLOWED_TYPES.includes(file.type)&&!isMov)throw new Error("Usá un video MP4, WebM o MOV.");if(file.size>50*1024*1024)throw new Error("El video no puede superar 50 MB.");const s=await fetch("/api/admin/video-oficial/upload-url",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fileName:file.name,mimeType:file.type})});const d=await s.json();if(!s.ok)throw new Error(d?.error||"No se pudo preparar la carga.");const body=new FormData();body.append("cacheControl","31536000");body.append("",file);const u=await fetch(d.signedUrl,{method:"PUT",body});if(!u.ok)throw new Error("No se pudo cargar el video.");formData.set("video_path",d.path);formData.set("source_type","upload");}formData.delete("video_file");const r=await fetch("/api/admin/video-oficial",{method:"POST",body:formData});if(!r.ok)throw new Error("No se pudo guardar la configuración.");window.location.href="/admin/video-oficial?guardado=1";}catch(e){setStatus(e instanceof Error?e.message:"Ocurrió un error.");setUploading(false)}}
 return <form onSubmit={handleSubmit} className="mt-8 space-y-6">
  {props.saved?<p className="rounded-xl bg-green-50 p-4 text-sm text-green-800">Video oficial actualizado correctamente.</p>:null}{status?<p className="rounded-xl bg-red-50 p-4 text-sm text-red-800">{status}</p>:null}
  <section className="rounded-2xl border border-brand-border bg-white p-6">
   <label className="flex items-center justify-between gap-4 rounded-xl border border-brand-border bg-brand-cream/40 px-4 py-4"><span><b className="block text-brand-forest">Mostrar esta sección en la página</b><small className="mt-1 block text-brand-muted">Opcional. Si desmarcás esta casilla, el video no aparecerá públicamente pero la configuración queda guardada.</small></span><input type="checkbox" name="enabled" defaultChecked={props.enabled} className="h-5 w-5 accent-[#123f31]"/></label>
   <div className="mt-6 grid gap-4 md:grid-cols-2"><label><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-[#4d493f]">Etiqueta superior</span><input name="eyebrow" defaultValue={props.eyebrow} className={inputClass}/></label><label><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-[#4d493f]">Título</span><input name="title" defaultValue={props.title} className={inputClass}/></label><label className="md:col-span-2"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-[#4d493f]">Descripción</span><textarea name="description" defaultValue={props.description} rows={3} className={`${inputClass} py-3`}/></label></div>
  </section>
  <section className="rounded-2xl border border-brand-border bg-white p-6"><h2 className="text-2xl font-semibold text-brand-forest">Cargar video oficial</h2><p className="mt-1 text-sm text-brand-muted">Admite MP4, WebM y MOV. Para máxima compatibilidad web recomendamos MP4 H.264, 1080p (1920×1080), relación 16:9. Máximo 50 MB.</p><label className="mt-5 block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-[#4d493f]">Archivo de video</span><input name="video_file" type="file" accept="video/mp4,video/webm,video/quicktime,.mov" className="block w-full rounded-xl border border-[#c9bea9] bg-white p-3 text-[#0b3b30]"/></label>{props.videoUrl&&props.sourceType==="upload"?<div className="mt-5 overflow-hidden rounded-2xl border border-brand-border bg-black"><video src={props.videoUrl} controls preload="metadata" className="aspect-video w-full object-contain"/></div>:null}</section>
  <section className="rounded-2xl border border-brand-border bg-white p-6"><h2 className="text-xl font-semibold text-brand-forest">Reproducción</h2><p className="mt-1 text-sm text-brand-muted">Elegí cómo querés que se comporte el video en la página.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><label className="flex items-center gap-3 rounded-xl border border-brand-border p-4"><input type="checkbox" name="autoplay" defaultChecked={props.autoplay} className="h-5 w-5 accent-[#123f31]"/><span><b className="block text-brand-forest">Reproducir solo</b><small className="text-brand-muted">Intenta iniciar automáticamente.</small></span></label><label className="flex items-center gap-3 rounded-xl border border-brand-border p-4"><input type="checkbox" name="sound_enabled" defaultChecked={props.soundEnabled} className="h-5 w-5 accent-[#123f31]"/><span><b className="block text-brand-forest">Sonido activo</b><small className="text-brand-muted">Inicia con audio cuando el navegador lo permite.</small></span></label><label className="flex items-center gap-3 rounded-xl border border-brand-border p-4"><input type="checkbox" name="loop" defaultChecked={props.loop} className="h-5 w-5 accent-[#123f31]"/><span><b className="block text-brand-forest">Repetir video</b><small className="text-brand-muted">Vuelve a empezar al finalizar.</small></span></label></div><p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-900"><b>Importante:</b> Chrome, Safari y otros navegadores pueden bloquear el autoplay con sonido hasta que la persona interactúe con la página. El sitio intentará reproducirlo con sonido; si el navegador lo bloquea, mostrará los controles para activarlo.</p></section>
  <details className="rounded-2xl border border-brand-border bg-white p-6"><summary className="cursor-pointer text-lg font-semibold text-brand-forest">Alternativa: usar enlace de YouTube</summary><label className="mt-4 block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-[#4d493f]">Enlace de YouTube</span><input name="youtube_url" type="url" defaultValue={props.youtubeUrl} className={inputClass}/></label><label className="mt-4 flex items-center gap-2 text-sm text-brand-forest"><input type="radio" name="source_type" value="youtube" defaultChecked={props.sourceType==="youtube"}/> Usar YouTube</label><input type="hidden" name="video_path" value=""/></details>
  <div className="flex justify-end"><button disabled={uploading} className="rounded-xl bg-brand-gold px-8 py-4 font-semibold text-brand-forest shadow-sm disabled:opacity-60">{uploading?"Cargando video...":"Guardar video oficial"}</button></div>
 </form>;
}
