"use client";

import { useEffect, useRef, useState } from "react";
import { Container, Eyebrow } from "@/components/ui/design";

type CampVideoPayload={enabled:boolean;eyebrow:string;title:string;description:string;sourceType:"youtube"|"upload"|"drive";videoId:string;videoUrl:string;driveEmbedUrl:string;thumbnailUrl:string;embedUrl:string;autoplay:boolean;soundEnabled:boolean;loop:boolean};

export default function CampVideoSection(){
 const[settings,setSettings]=useState<CampVideoPayload|null>(null);const[showPlayer,setShowPlayer]=useState(false);const[audioBlocked,setAudioBlocked]=useState(false);const videoRef=useRef<HTMLVideoElement>(null);
 useEffect(()=>{fetch("/api/camp-video",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(setSettings).catch(()=>{})},[]);
 useEffect(()=>{const video=videoRef.current;if(!video||!settings?.autoplay)return;video.muted=!settings.soundEnabled;const attempt=video.play();if(attempt)attempt.catch(async()=>{if(settings.soundEnabled){video.muted=true;setAudioBlocked(true);try{await video.play()}catch{}}});},[settings]);
 if(!settings?.enabled)return null;const isUpload=settings.sourceType==="upload"&&Boolean(settings.videoUrl);const isYoutube=settings.sourceType==="youtube"&&Boolean(settings.videoId);const isDrive=settings.sourceType==="drive"&&Boolean(settings.driveEmbedUrl);if(!isUpload&&!isYoutube&&!isDrive)return null;
 const youtubeParams=`autoplay=${settings.autoplay?1:0}&mute=${settings.soundEnabled?0:1}&loop=${settings.loop?1:0}${settings.loop?`&playlist=${settings.videoId}`:""}`;
 return <section id="video-completo" className="scroll-mt-24 bg-brand-warmWhite py-12 sm:py-16"><Container><article className="overflow-hidden rounded-[1.7rem] bg-brand-forestDark text-white lg:grid lg:grid-cols-[.42fr_.58fr]"><div className="flex flex-col justify-center p-6 sm:p-8 lg:p-10"><Eyebrow className="text-brand-gold">{settings.eyebrow}</Eyebrow><h2 className="mt-3 text-3xl font-semibold tracking-[-.03em] sm:text-4xl">{settings.title}</h2><p className="mt-4 text-sm leading-6 text-white/70 sm:text-base">{settings.description}</p></div><div className="relative aspect-video overflow-hidden bg-black lg:aspect-auto lg:min-h-[360px]">
 {isDrive?<iframe src={settings.driveEmbedUrl} title={settings.title||"Video oficial Gracia Camp"} className="h-full w-full border-0" allow="autoplay; fullscreen" allowFullScreen/>:isUpload?<><video ref={videoRef} src={settings.videoUrl} controls playsInline preload="auto" loop={settings.loop} className="h-full w-full bg-black object-contain">Tu navegador no puede reproducir este video.</video>{audioBlocked&&settings.soundEnabled?<button type="button" onClick={()=>{const v=videoRef.current;if(v){v.muted=false;v.play().catch(()=>{});setAudioBlocked(false)}}} className="absolute bottom-4 left-1/2 -translate-x-1/2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-brand-forest shadow-lg">🔊 Activar sonido</button>:null}</>:showPlayer||settings.autoplay?<iframe src={`${settings.embedUrl}?${youtubeParams}`} title={settings.title||"Video oficial Gracia Camp"} className="h-full w-full" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/>:<button type="button" onClick={()=>setShowPlayer(true)} className="group relative h-full w-full overflow-hidden" aria-label="Reproducir video oficial de Gracia Camp"><img src={settings.thumbnailUrl} alt="Video oficial Gracia Camp" className="absolute inset-0 h-full w-full object-cover opacity-70"/><span className="absolute inset-0 flex items-center justify-center"><span className="flex h-16 w-16 items-center justify-center rounded-full border border-white/70 bg-black/35 text-xl text-white backdrop-blur transition group-hover:scale-105">▶</span></span></button>}
 </div></article></Container></section>;
}
