import Link from "next/link";
import { revalidatePath } from "next/cache";
import { createTeam, listTeamMembers, listTeams } from "@/lib/camp-management";

export const dynamic="force-dynamic";
const field="min-h-11 rounded-xl border border-brand-border bg-white px-3 text-sm text-brand-forest placeholder:text-brand-muted/70 focus:border-brand-gold focus:outline-none focus:ring-2 focus:ring-brand-gold/20";

async function createTeamAction(formData:FormData){"use server";const name=String(formData.get("name")||"").trim();if(!name)return;await createTeam({name,colorName:String(formData.get("colorName")||name).trim(),colorHex:String(formData.get("colorHex")||"#0E3B31")});revalidatePath("/admin/equipos");}

export default async function EquiposPage(){const[teams,members]=await Promise.all([listTeams().catch(()=>[]),listTeamMembers().catch(()=>[])]);const ranking=[...teams].sort((a,b)=>b.points-a.points);const assigned=members.filter(m=>m.team_id).length;return <main className="p-5 sm:p-8 lg:p-10">
  <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-brand-gold">Gestión</p><h1 className="mt-2 text-4xl font-semibold text-brand-forest">Equipos</h1><p className="mt-2 text-brand-muted">Elegí un equipo para ver integrantes o administrar sus puntos.</p></div><div className="flex gap-3 text-sm text-brand-muted"><span>{teams.length} equipos</span><span>·</span><span>{assigned} asignados</span></div></div>

  <section className="mt-8 overflow-hidden rounded-2xl border border-brand-border bg-white">
    {ranking.map((team,index)=>{const count=members.filter(m=>m.team_id===team.id).length;return <Link key={team.id} href={`/admin/equipos/${team.id}`} className="grid gap-4 border-b border-brand-border p-5 transition last:border-b-0 hover:bg-brand-cream/40 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div className="flex items-center gap-4"><span className="h-11 w-11 shrink-0 rounded-full border border-black/10" style={{backgroundColor:team.color_hex}}/><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-brand-gold">#{index+1} Ranking</p><h2 className="text-xl font-semibold text-brand-forest">{team.name}</h2><p className="mt-1 text-sm text-brand-muted">{count} {count===1?"integrante":"integrantes"}</p></div></div><div className="sm:text-right"><p className="text-xs uppercase tracking-[.12em] text-brand-muted">Puntos</p><p className="text-2xl font-bold text-brand-forest">{team.points}</p></div><span className="inline-flex min-h-10 items-center justify-center rounded-full border border-brand-border px-4 text-sm font-semibold text-brand-forest">Ver equipo →</span></Link>})}
    {!teams.length?<div className="p-6 text-sm text-brand-muted">Todavía no hay equipos creados.</div>:null}
  </section>

  <details className="mt-6 rounded-2xl border border-brand-border bg-white"><summary className="cursor-pointer list-none p-5 font-semibold text-brand-forest">+ Crear un equipo nuevo</summary><form action={createTeamAction} className="grid gap-4 border-t border-brand-border p-5 md:grid-cols-3"><label className="grid gap-2 text-sm font-semibold text-brand-forest">Nombre<input name="name" required placeholder="Ej. Violeta" className={field}/></label><label className="grid gap-2 text-sm font-semibold text-brand-forest">Nombre del color<input name="colorName" placeholder="Violeta" className={field}/></label><label className="grid gap-2 text-sm font-semibold text-brand-forest">Color<input name="colorHex" type="color" defaultValue="#0E3B31" className="h-11 w-full rounded-xl border border-brand-border bg-white p-1"/></label><button className="min-h-11 rounded-xl bg-brand-forest px-5 font-semibold text-white md:col-span-3">Crear equipo</button></form></details>
</main>}
