import { revalidatePath } from "next/cache";

import { addTeamPoints, createTeam, deleteTeam, listPointMovements, listTeams } from "@/lib/camp-management";

export const dynamic="force-dynamic";

async function createTeamAction(formData:FormData){"use server";const name=String(formData.get("name")||"").trim();if(!name)return;await createTeam({name,colorName:String(formData.get("colorName")||name).trim(),colorHex:String(formData.get("colorHex")||"#0E3B31")});revalidatePath("/admin/equipos");}
async function deleteTeamAction(formData:FormData){"use server";const id=String(formData.get("id")||"");if(id)await deleteTeam(id);revalidatePath("/admin/equipos");}
async function pointsAction(formData:FormData){"use server";const teamId=String(formData.get("teamId")||"");const points=Number(formData.get("points")||0);if(!teamId||!Number.isFinite(points)||points===0)return;await addTeamPoints(teamId,points,String(formData.get("reason")||"").trim());revalidatePath("/admin/equipos");}

export default async function EquiposPage(){const[teams,movements]=await Promise.all([listTeams().catch(()=>[]),listPointMovements(20).catch(()=>[])]);const ranking=[...teams].sort((a,b)=>b.points-a.points);return <main className="p-5 sm:p-8 lg:p-10">
  <div><p className="text-xs font-semibold uppercase tracking-[.2em] text-brand-gold">Gestión</p><h1 className="mt-2 text-4xl font-semibold text-brand-forest">Equipos</h1><p className="mt-2 text-brand-muted">Creá equipos, elegí sus colores y administrá los puntos del campamento.</p></div>
  <section className="mt-8 rounded-2xl border border-brand-border bg-white p-5 sm:p-7"><h2 className="text-xl font-semibold text-brand-forest">Agregar equipo</h2><form action={createTeamAction} className="mt-5 grid gap-4 md:grid-cols-3"><label className="grid gap-2 text-sm font-semibold text-brand-forest">Nombre<input name="name" required placeholder="Ej. Violeta" className="min-h-12 rounded-xl border border-brand-border px-4 font-normal"/></label><label className="grid gap-2 text-sm font-semibold text-brand-forest">Nombre del color<input name="colorName" placeholder="Violeta" className="min-h-12 rounded-xl border border-brand-border px-4 font-normal"/></label><label className="grid gap-2 text-sm font-semibold text-brand-forest">Color<input name="colorHex" type="color" defaultValue="#0E3B31" className="h-12 w-full rounded-xl border border-brand-border bg-white p-1"/></label><button className="min-h-12 rounded-xl bg-brand-forest px-5 font-semibold text-white md:col-span-3">Agregar equipo</button></form></section>
  <section className="mt-6"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{ranking.map((team,index)=><article key={team.id} className="rounded-2xl border border-brand-border bg-white p-5"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="h-10 w-10 rounded-full border border-black/10" style={{backgroundColor:team.color_hex}}/><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-brand-gold">#{index+1} Ranking</p><h2 className="text-2xl font-semibold text-brand-forest">{team.name}</h2></div></div><form action={deleteTeamAction}><input type="hidden" name="id" value={team.id}/><button className="rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Eliminar</button></form></div><div className="mt-5 rounded-xl bg-brand-cream p-4"><p className="text-xs uppercase tracking-[.14em] text-brand-muted">Puntaje actual</p><p className="mt-1 text-4xl font-bold text-brand-forest">{team.points}</p></div><form action={pointsAction} className="mt-4 grid gap-2"><input type="hidden" name="teamId" value={team.id}/><div className="grid grid-cols-2 gap-2"><button name="points" value="10" className="min-h-10 rounded-xl bg-brand-forest text-sm font-semibold text-white">+10 puntos</button><button name="points" value="-10" className="min-h-10 rounded-xl border border-brand-border text-sm font-semibold text-brand-forest">-10 puntos</button></div><div className="grid grid-cols-[1fr_auto] gap-2"><input name="reason" placeholder="Motivo (opcional)" className="min-h-10 rounded-xl border border-brand-border px-3 text-sm"/><input name="points" type="number" placeholder="Pts" className="w-24 min-h-10 rounded-xl border border-brand-border px-3 text-sm"/></div><button className="min-h-10 rounded-xl bg-brand-cream text-sm font-semibold text-brand-forest">Guardar puntaje manual</button></form></article>)}{!teams.length?<p className="text-sm text-brand-muted">Todavía no hay equipos creados.</p>:null}</div></section>
  <section className="mt-8 rounded-2xl border border-brand-border bg-white p-5 sm:p-7"><h2 className="text-xl font-semibold text-brand-forest">Últimos movimientos</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-brand-border text-xs uppercase tracking-wider text-brand-muted"><tr><th className="py-3">Equipo</th><th className="py-3">Puntos</th><th className="py-3">Motivo</th><th className="py-3">Fecha</th></tr></thead><tbody className="divide-y divide-brand-border">{movements.map(m=>{const team=teams.find(t=>t.id===m.team_id);return <tr key={m.id}><td className="py-3 font-semibold text-brand-forest">{team?.name||"Equipo"}</td><td className={`py-3 font-bold ${m.points>=0?"text-green-700":"text-red-700"}`}>{m.points>0?`+${m.points}`:m.points}</td><td className="py-3 text-brand-muted">{m.reason||"—"}</td><td className="py-3 text-brand-muted">{new Date(m.created_at).toLocaleString("es-PY")}</td></tr>})}</tbody></table>{!movements.length?<p className="py-5 text-sm text-brand-muted">Todavía no hay movimientos de puntos.</p>:null}</div></section>
</main>}
