import { revalidatePath } from "next/cache";
import { addTeamPoints, assignMemberToTeam, createTeam, deleteTeam, listPointMovements, listTeamMembers, listTeams } from "@/lib/camp-management";

export const dynamic="force-dynamic";
const field="min-h-11 rounded-xl border border-brand-border bg-white px-3 text-sm text-brand-forest placeholder:text-brand-muted/70 focus:border-brand-gold focus:outline-none focus:ring-2 focus:ring-brand-gold/20";
async function createTeamAction(formData:FormData){"use server";const name=String(formData.get("name")||"").trim();if(!name)return;await createTeam({name,colorName:String(formData.get("colorName")||name).trim(),colorHex:String(formData.get("colorHex")||"#0E3B31")});revalidatePath("/admin/equipos");}
async function deleteTeamAction(formData:FormData){"use server";const id=String(formData.get("id")||"");if(id)await deleteTeam(id);revalidatePath("/admin/equipos");}
async function pointsAction(formData:FormData){"use server";const teamId=String(formData.get("teamId")||"");const points=Number(formData.get("points")||0);if(!teamId||!Number.isFinite(points)||points===0)return;await addTeamPoints(teamId,points,String(formData.get("reason")||"").trim());revalidatePath("/admin/equipos");}
async function moveMemberAction(formData:FormData){"use server";const memberId=String(formData.get("memberId")||"");const teamId=String(formData.get("teamId")||"");if(memberId)await assignMemberToTeam(memberId,teamId||null);revalidatePath("/admin/equipos");}
async function removeMemberAction(formData:FormData){"use server";const memberId=String(formData.get("memberId")||"");if(memberId)await assignMemberToTeam(memberId,null);revalidatePath("/admin/equipos");}

export default async function EquiposPage(){const[teams,movements,members]=await Promise.all([listTeams().catch(()=>[]),listPointMovements(20).catch(()=>[]),listTeamMembers().catch(()=>[])]);const ranking=[...teams].sort((a,b)=>b.points-a.points);const unassigned=members.filter(m=>!m.team_id);return <main className="p-5 sm:p-8 lg:p-10">
<div><p className="text-xs font-semibold uppercase tracking-[.2em] text-brand-gold">Gestión</p><h1 className="mt-2 text-4xl font-semibold text-brand-forest">Equipos</h1><p className="mt-2 text-brand-muted">Administrá integrantes, colores y puntos del campamento.</p></div>
<section className="mt-8 rounded-2xl border border-brand-border bg-white p-5 sm:p-7"><h2 className="text-xl font-semibold text-brand-forest">Agregar equipo</h2><form action={createTeamAction} className="mt-5 grid gap-4 md:grid-cols-3"><label className="grid gap-2 text-sm font-semibold text-brand-forest">Nombre<input name="name" required placeholder="Ej. Violeta" className={field}/></label><label className="grid gap-2 text-sm font-semibold text-brand-forest">Nombre del color<input name="colorName" placeholder="Violeta" className={field}/></label><label className="grid gap-2 text-sm font-semibold text-brand-forest">Color<input name="colorHex" type="color" defaultValue="#0E3B31" className="h-11 w-full rounded-xl border border-brand-border bg-white p-1"/></label><button className="min-h-11 rounded-xl bg-brand-forest px-5 font-semibold text-white md:col-span-3">Agregar equipo</button></form></section>
{unassigned.length?<section className="mt-6 rounded-2xl border border-brand-border bg-white p-5"><h2 className="font-semibold text-brand-forest">Sin equipo <span className="ml-2 text-sm font-normal text-brand-muted">{unassigned.length}</span></h2><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{unassigned.map(m=><form key={m.id} action={moveMemberAction} className="flex items-center gap-2 rounded-xl bg-brand-cream p-3"><input type="hidden" name="memberId" value={m.id}/><div className="min-w-0 flex-1"><p className="truncate font-semibold text-brand-forest">{m.nombre} {m.apellido}</p><p className="text-xs text-brand-muted">{m.edad?`${m.edad} años`:"Inscripto"}</p></div><select name="teamId" required className={`${field} w-32`} defaultValue=""><option value="" disabled>Asignar</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button className="rounded-lg bg-brand-forest px-3 py-2 text-xs font-semibold text-white">Mover</button></form>)}</div></section>:null}
<section className="mt-6"><div className="grid gap-4 lg:grid-cols-2">{ranking.map((team,index)=>{const teamMembers=members.filter(m=>m.team_id===team.id);return <article key={team.id} className="rounded-2xl border border-brand-border bg-white p-5"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="h-10 w-10 shrink-0 rounded-full border border-black/10" style={{backgroundColor:team.color_hex}}/><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-brand-gold">#{index+1} Ranking · {teamMembers.length} integrantes</p><h2 className="text-2xl font-semibold text-brand-forest">{team.name}</h2></div></div><form action={deleteTeamAction}><input type="hidden" name="id" value={team.id}/><button className="rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Eliminar equipo</button></form></div>
<div className="mt-5 rounded-xl bg-brand-cream p-4"><p className="text-xs uppercase tracking-[.14em] text-brand-muted">Puntaje actual</p><p className="mt-1 text-4xl font-bold text-brand-forest">{team.points}</p></div>
<div className="mt-5"><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold text-brand-forest">Integrantes</h3><span className="text-xs text-brand-muted">Mover o quitar</span></div><div className="grid gap-2">{teamMembers.map(m=><div key={m.id} className="rounded-xl border border-brand-border p-3"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold text-brand-forest">{m.nombre} {m.apellido}</p><p className="text-xs text-brand-muted">{m.edad?`${m.edad} años`:"Participante"}</p></div><form action={removeMemberAction}><input type="hidden" name="memberId" value={m.id}/><button className="text-xs font-semibold text-red-700 hover:underline">Quitar</button></form></div><form action={moveMemberAction} className="mt-2 flex gap-2"><input type="hidden" name="memberId" value={m.id}/><select name="teamId" className={`${field} min-w-0 flex-1`} defaultValue={team.id}>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button className="rounded-xl border border-brand-border px-4 text-xs font-semibold text-brand-forest">Mover</button></form></div>)}{!teamMembers.length?<div className="rounded-xl border border-dashed border-brand-border p-4 text-sm text-brand-muted">Todavía no hay integrantes en este equipo.</div>:null}</div></div>
<form action={pointsAction} className="mt-5 grid gap-2 border-t border-brand-border pt-5"><input type="hidden" name="teamId" value={team.id}/><div className="grid grid-cols-2 gap-2"><button name="points" value="10" className="min-h-10 rounded-xl bg-brand-forest text-sm font-semibold text-white">+10 puntos</button><button name="points" value="-10" className="min-h-10 rounded-xl border border-brand-border text-sm font-semibold text-brand-forest">-10 puntos</button></div><div className="grid grid-cols-[1fr_88px] gap-2"><input name="reason" placeholder="Motivo (opcional)" className={field}/><input name="points" type="number" placeholder="Pts" className={field}/></div><button className="min-h-10 rounded-xl bg-brand-cream text-sm font-semibold text-brand-forest">Guardar puntaje manual</button></form></article>})}</div></section>
<section className="mt-8 rounded-2xl border border-brand-border bg-white p-5 sm:p-7"><h2 className="text-xl font-semibold text-brand-forest">Últimos movimientos</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-brand-border text-xs uppercase tracking-wider text-brand-muted"><tr><th className="py-3">Equipo</th><th>Puntos</th><th>Motivo</th><th>Fecha</th></tr></thead><tbody className="divide-y divide-brand-border">{movements.map(m=>{const team=teams.find(t=>t.id===m.team_id);return <tr key={m.id}><td className="py-3 font-semibold text-brand-forest">{team?.name||"Equipo"}</td><td className={m.points>=0?"font-bold text-green-700":"font-bold text-red-700"}>{m.points>0?`+${m.points}`:m.points}</td><td className="text-brand-muted">{m.reason||"—"}</td><td className="text-brand-muted">{new Date(m.created_at).toLocaleString("es-PY")}</td></tr>})}</tbody></table>{!movements.length?<p className="py-5 text-sm text-brand-muted">Todavía no hay movimientos de puntos.</p>:null}</div></section>
</main>}
