import Link from "next/link";
import { notFound } from "next/navigation";
import { revalidatePath } from "next/cache";
import { addTeamPoints, assignMemberToTeam, deleteTeam, listPointMovements, listTeamMembers, listTeams } from "@/lib/camp-management";

export const dynamic="force-dynamic";
const field="min-h-11 rounded-xl border border-brand-border bg-white px-3 text-sm text-brand-forest placeholder:text-brand-muted/70 focus:border-brand-gold focus:outline-none focus:ring-2 focus:ring-brand-gold/20";

async function moveMemberAction(formData:FormData){"use server";const memberId=String(formData.get("memberId")||"");const teamId=String(formData.get("teamId")||"");if(memberId)await assignMemberToTeam(memberId,teamId||null);revalidatePath(`/admin/equipos/${String(formData.get("currentTeamId")||"")}`);revalidatePath("/admin/equipos");}
async function removeMemberAction(formData:FormData){"use server";const memberId=String(formData.get("memberId")||"");const currentTeamId=String(formData.get("currentTeamId")||"");if(memberId)await assignMemberToTeam(memberId,null);revalidatePath(`/admin/equipos/${currentTeamId}`);revalidatePath("/admin/equipos");}
async function pointsAction(formData:FormData){"use server";const teamId=String(formData.get("teamId")||"");const points=Number(formData.get("points")||0);if(!teamId||!Number.isFinite(points)||points===0)return;await addTeamPoints(teamId,points,String(formData.get("reason")||"").trim());revalidatePath(`/admin/equipos/${teamId}`);revalidatePath("/admin/equipos");}
async function deleteTeamAction(formData:FormData){"use server";const id=String(formData.get("id")||"");if(id)await deleteTeam(id);revalidatePath("/admin/equipos");}

export default async function EquipoDetallePage({params}:{params:{id:string}}){const[teams,members,movements]=await Promise.all([listTeams().catch(()=>[]),listTeamMembers().catch(()=>[]),listPointMovements(50).catch(()=>[])]);const team=teams.find(t=>t.id===params.id);if(!team)notFound();const teamMembers=members.filter(m=>m.team_id===team.id);const unassigned=members.filter(m=>!m.team_id);const teamMovements=movements.filter(m=>m.team_id===team.id).slice(0,10);return <main className="p-5 sm:p-8 lg:p-10">
  <Link href="/admin/equipos" className="text-sm font-semibold text-brand-forest">← Volver a equipos</Link>
  <div className="mt-5 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-center gap-4"><span className="h-14 w-14 shrink-0 rounded-full border border-black/10" style={{backgroundColor:team.color_hex}}/><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand-gold">Equipo</p><h1 className="mt-1 text-4xl font-semibold text-brand-forest">{team.name}</h1><p className="mt-1 text-sm text-brand-muted">{teamMembers.length} {teamMembers.length===1?"integrante":"integrantes"}</p></div></div><div className="rounded-2xl bg-brand-cream px-6 py-4"><p className="text-xs uppercase tracking-[.12em] text-brand-muted">Puntaje</p><p className="text-4xl font-bold text-brand-forest">{team.points}</p></div></div>

  <section className="mt-8 rounded-2xl border border-brand-border bg-white p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold text-brand-forest">Integrantes</h2><p className="mt-1 text-sm text-brand-muted">Mové o quitá personas de este equipo.</p></div></div><div className="mt-5 divide-y divide-brand-border">{teamMembers.map(m=><div key={m.id} className="py-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-brand-forest">{m.nombre} {m.apellido}</p><p className="text-sm text-brand-muted">{m.edad?`${m.edad} años`:"Participante"}</p></div><div className="flex flex-col gap-2 sm:flex-row"><form action={moveMemberAction} className="flex gap-2"><input type="hidden" name="memberId" value={m.id}/><input type="hidden" name="currentTeamId" value={team.id}/><select name="teamId" className={`${field} min-w-[150px]`} defaultValue={team.id}>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button className="rounded-xl border border-brand-border px-4 text-sm font-semibold text-brand-forest">Mover</button></form><form action={removeMemberAction}><input type="hidden" name="memberId" value={m.id}/><input type="hidden" name="currentTeamId" value={team.id}/><button className="min-h-11 rounded-xl px-3 text-sm font-semibold text-red-700">Quitar</button></form></div></div></div>)}{!teamMembers.length?<p className="py-5 text-sm text-brand-muted">Este equipo todavía no tiene integrantes.</p>:null}</div></section>

  {unassigned.length?<section className="mt-5 rounded-2xl border border-brand-border bg-white p-5 sm:p-6"><h2 className="text-lg font-semibold text-brand-forest">Agregar participante</h2><p className="mt-1 text-sm text-brand-muted">Personas que todavía no tienen equipo.</p><div className="mt-4 grid gap-2 md:grid-cols-2">{unassigned.map(m=><form key={m.id} action={moveMemberAction} className="flex items-center gap-3 rounded-xl bg-brand-cream p-3"><input type="hidden" name="memberId" value={m.id}/><input type="hidden" name="currentTeamId" value={team.id}/><input type="hidden" name="teamId" value={team.id}/><div className="min-w-0 flex-1"><p className="truncate font-semibold text-brand-forest">{m.nombre} {m.apellido}</p><p className="text-xs text-brand-muted">{m.edad?`${m.edad} años`:"Inscripto"}</p></div><button className="rounded-xl bg-brand-forest px-4 py-2 text-sm font-semibold text-white">Agregar</button></form>)}</div></section>:null}

  <section className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><article className="rounded-2xl border border-brand-border bg-white p-5 sm:p-6"><h2 className="text-xl font-semibold text-brand-forest">Puntaje</h2><p className="mt-1 text-sm text-brand-muted">Usá los botones rápidos o cargá otro valor.</p><form action={pointsAction} className="mt-5 grid gap-3"><input type="hidden" name="teamId" value={team.id}/><div className="grid grid-cols-2 gap-2"><button name="points" value="10" className="min-h-11 rounded-xl bg-brand-forest font-semibold text-white">+10</button><button name="points" value="-10" className="min-h-11 rounded-xl border border-brand-border font-semibold text-brand-forest">-10</button></div><input name="reason" placeholder="Motivo (opcional)" className={field}/><div className="grid grid-cols-[1fr_auto] gap-2"><input name="points" type="number" placeholder="Ej. 25 o -15" className={field}/><button className="rounded-xl bg-brand-cream px-5 font-semibold text-brand-forest">Guardar</button></div></form></article><article className="rounded-2xl border border-brand-border bg-white p-5 sm:p-6"><h2 className="text-xl font-semibold text-brand-forest">Últimos movimientos</h2><div className="mt-4 divide-y divide-brand-border">{teamMovements.map(m=><div key={m.id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm text-brand-muted">{m.reason||"Sin motivo"}</p><p className="mt-1 text-xs text-brand-muted/70">{new Date(m.created_at).toLocaleString("es-PY")}</p></div><strong className={m.points>=0?"text-green-700":"text-red-700"}>{m.points>0?`+${m.points}`:m.points}</strong></div>)}{!teamMovements.length?<p className="py-5 text-sm text-brand-muted">Todavía no hay movimientos.</p>:null}</div></article></section>

  <details className="mt-8 border-t border-red-100 pt-5"><summary className="cursor-pointer text-sm font-semibold text-red-700">Opciones avanzadas</summary><div className="mt-4 rounded-xl bg-red-50 p-4"><p className="text-sm text-red-800">Eliminar este equipo no elimina a los participantes; quedan sin equipo.</p><form action={deleteTeamAction} className="mt-3"><input type="hidden" name="id" value={team.id}/><button className="rounded-xl border border-red-300 bg-white px-4 py-2 text-sm font-semibold text-red-700">Eliminar equipo</button></form></div></details>
</main>}
