"use client";

import Link from "next/link";

import Header from "@/components/Header";
import PreacherSection from "@/components/PreacherSection";
import MerchSectionPublic from "@/components/MerchSectionPublic";
import CampVideoSection from "@/components/CampVideoSection";
import LaunchReveal from "@/components/LaunchReveal";
import { ButtonLink, Container, Eyebrow } from "@/components/ui/design";

function HeroVideo() {
  return (
    <section className="relative isolate overflow-hidden bg-black text-white">
      <div className="absolute inset-0 -z-30 overflow-hidden">
        <video autoPlay muted loop playsInline preload="metadata" className="pointer-events-none absolute inset-0 h-full w-full object-cover" aria-hidden="true">
          <source src="/videos/video%20detras.mp4" type="video/mp4" />
        </video>
      </div>
      <div className="absolute inset-0 -z-20 bg-black/55" />
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_center,transparent_0%,rgba(0,0,0,.18)_48%,rgba(0,0,0,.68)_100%)]" />
      <Container className="flex min-h-[620px] flex-col items-center justify-center py-16 text-center sm:min-h-[700px] lg:min-h-[760px]"><div className="max-w-5xl"><p className="text-xs font-bold uppercase tracking-[.28em] text-brand-gold sm:text-sm">Ministerio de Jóvenes CBG</p><h1 className="mt-5 text-[clamp(3.7rem,10vw,8.2rem)] font-black uppercase leading-[.84] tracking-[-.055em]">Gracia Camp <span className="block text-brand-gold sm:inline">2026</span></h1><p className="mx-auto mt-7 max-w-2xl text-lg font-medium leading-7 text-white/90 sm:text-2xl sm:leading-9">4 días para salir de la rutina y vivir lo que realmente importa.</p><div className="mt-8 flex justify-center"><ButtonLink href="/registro" variant="light" className="min-h-12 px-8 text-base">Inscribirme ahora</ButtonLink></div></div></Container>
    </section>
  );
}

function KeyInfo(){const items=[["Fecha","03–06","Diciembre 2026"],["Lugar","San Bernardino","Rancho Alegre"],["Precio","Gs. 450.000","Por persona"],["Cupos","Limitados","Inscripciones abiertas"]];return <section className="relative z-10 -mt-8 pb-8 sm:-mt-10"><Container><div className="grid overflow-hidden rounded-[1.6rem] border border-brand-border bg-brand-warmWhite shadow-xl shadow-black/10 sm:grid-cols-2 lg:grid-cols-4">{items.map(([label,value,sub],index)=><div key={label} className={`p-5 sm:p-6 ${index?"border-t border-brand-border sm:border-t-0 sm:border-l":""}`}><p className="text-[10px] font-bold uppercase tracking-[.18em] text-brand-gold">{label}</p><p className="mt-2 text-xl font-semibold text-brand-forest sm:text-2xl">{value}</p><p className="mt-1 text-sm text-brand-muted">{sub}</p></div>)}</div></Container></section>}
function Pillars(){const items=[["Exaltar a Dios",""],["Predicar el evangelio",""],["Edificar a los creyentes","con la enseñanza de Su Palabra."]];return <section className="bg-brand-warmWhite py-8 sm:py-12"><Container><div className="mb-5 text-center sm:mb-8"><h2 className="text-3xl font-semibold text-brand-forest sm:text-4xl">Tres propósitos</h2></div><div className="-mx-5 flex snap-x snap-mandatory gap-3 overflow-x-auto px-5 pb-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden sm:mx-0 sm:grid sm:grid-cols-3 sm:overflow-visible sm:px-0 sm:pb-0">{items.map(([title,text],index)=><article key={title} className="min-w-[84%] snap-center rounded-[1.4rem] border border-brand-border bg-white p-5 sm:min-w-0 sm:p-6"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-brand-forest text-sm font-bold text-white">0{index+1}</div><h3 className="mt-4 text-xl font-semibold text-brand-forest">{title}</h3>{text?<p className="mt-2 text-sm leading-6 text-brand-muted">{text}</p>:null}</article>)}</div><p className="mt-2 text-center text-[11px] text-brand-muted sm:hidden">Deslizá para ver los 3 propósitos →</p></Container></section>}
function FAQ(){const items=[["¿Cómo me inscribo?","Completá el formulario de registro y seguí las indicaciones del equipo."],["¿Qué incluye?","La organización comunicará el detalle completo y las recomendaciones antes del campamento."],["¿Dónde veo el reglamento?","Podés abrirlo desde el botón al final de esta página."]];return <section className="bg-brand-cream py-12 sm:py-16"><Container className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><div><Eyebrow>Preguntas frecuentes</Eyebrow><h2 className="mt-2 text-3xl font-semibold text-brand-forest sm:text-4xl">¿Tenés dudas?</h2><p className="mt-3 max-w-md text-sm leading-6 text-brand-muted">Encontrá rápido las respuestas antes de reservar tu lugar.</p></div><div className="grid gap-2">{items.map(([q,a])=><details key={q} className="group rounded-xl border border-brand-border bg-white px-4 py-4"><summary className="cursor-pointer list-none text-sm font-semibold text-brand-forest sm:text-base">{q}<span className="float-right text-brand-gold group-open:rotate-45">+</span></summary><p className="mt-3 pr-5 text-sm leading-6 text-brand-muted">{a}</p></details>)}</div></Container></section>}
function CTA(){return <section className="bg-brand-forest py-12 text-white sm:py-16"><Container className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-brand-gold">No te lo pierdas</p><h2 className="mt-2 max-w-3xl text-3xl font-semibold leading-[1.04] sm:text-4xl lg:text-5xl">Inscribite hoy y asegurá tu lugar.</h2><p className="mt-3 text-sm text-white/70">03–06 de diciembre · Gs. 450.000 · cupos limitados.</p></div><div className="flex flex-col gap-2 sm:flex-row lg:flex-col"><ButtonLink href="/registro" variant="light" className="min-h-11 px-7 text-sm">Inscribirme ahora</ButtonLink><ButtonLink href="/reglamento" variant="secondary" className="min-h-11 border-white/25 px-7 text-sm text-white">Reglamento</ButtonLink></div></Container></section>}
function Footer(){return <footer className="bg-brand-forestDark py-6 text-white"><Container className="flex flex-col gap-2 text-xs text-white/50 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-white">Ministerio de Jóvenes CBG</p><p className="mt-1">Gracia Camp 2026</p></div><p>© 2026 Ministerio de Jóvenes CBG.</p></Container></footer>}
function StickyMobileActions(){return <div className="fixed inset-x-0 bottom-0 z-40 border-t border-brand-border bg-brand-warmWhite/95 p-2.5 backdrop-blur md:hidden"><Link href="/registro" className="flex min-h-11 items-center justify-center rounded-full bg-brand-forest px-4 text-sm font-semibold text-white">Inscribirme</Link></div>}

export default function CampamentoPage(){return <div className="min-h-screen bg-brand-warmWhite pb-16 text-brand-ink antialiased md:pb-0"><LaunchReveal/><Header/><main><HeroVideo/><KeyInfo/><Pillars/><PreacherSection/><MerchSectionPublic/><CampVideoSection/><FAQ/><CTA/></main><Footer/><StickyMobileActions/></div>}
