"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

import Header from "@/components/Header";
import PreacherSection from "@/components/PreacherSection";
import MerchSectionPublic from "@/components/MerchSectionPublic";
import { ButtonLink, Container, Eyebrow } from "@/components/ui/design";

const MAPS_URL = "https://maps.app.goo.gl/bVdDJtbaZFsJN7Eo7";
const YOUTUBE_VIDEO_ID = "_EpTnktKT-o";
const CAMP_PRICE = 400000;
const formatPrice=(value:number)=>`Gs. ${value.toLocaleString("es-PY")}`;

function QuickNav(){return <div className="sticky top-[58px] z-30 border-y border-brand-border bg-brand-warmWhite/95 backdrop-blur sm:top-[64px] lg:top-[68px]"><Container className="-mx-1 flex snap-x gap-1.5 overflow-x-auto py-2 text-[11px] [scrollbar-width:none] sm:mx-0 sm:gap-2 sm:text-sm">{[["Info","#info"],["Predicador","#predicador"],["Merch","#remera"],["Lugar + Video","#lugar"],["Inscripción","#inscripcion"]].map(([label,href])=><a key={href} href={href} className="snap-start whitespace-nowrap rounded-full border border-brand-border bg-white px-3 py-1.5 font-semibold text-brand-forest sm:px-4 sm:py-2">{label}</a>)}</Container></div>}

function InfoSection(){const facts=[["Fecha","03 al 06 de diciembre"],["Precio",formatPrice(CAMP_PRICE)],["Lugar","Nueva ubicación 2026"],["Cupos","Limitados"]];const exp=[["Palabra","Escuchar, preguntar y llevar la fe a la vida real."],["Comunidad","Amistades y conversaciones que se viven juntos."],["Aventura","Salir de la rutina y crear recuerdos con propósito."]];return <section id="info" className="scroll-mt-24 bg-brand-cream py-8 sm:py-12 lg:py-14"><Container><div className="max-w-3xl"><Eyebrow>Información clave</Eyebrow><h2 className="mt-2 text-2xl font-semibold leading-[1.04] tracking-[-.035em] text-brand-forest sm:text-4xl lg:text-5xl">Todo lo que necesitás saber, en un solo lugar.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-brand-muted sm:text-base">Fecha, precio, ubicación y cupos, sin repetir información.</p></div><div className="mt-5 grid grid-cols-2 gap-2.5 lg:grid-cols-4">{facts.map(([label,value])=><div key={label} className="rounded-xl border border-brand-border bg-white p-3.5 sm:rounded-2xl sm:p-5"><p className="text-[9px] font-bold uppercase tracking-[.14em] text-brand-gold">{label}</p><p className="mt-1.5 text-sm font-semibold leading-tight text-brand-forest sm:text-lg">{value}</p>{label==="Lugar"?<a href={MAPS_URL} target="_blank" rel="noopener noreferrer" className="mt-1.5 inline-flex text-[10px] font-semibold text-brand-forest underline underline-offset-4">Abrir Maps</a>:null}</div>)}</div><div className="-mx-4 mt-4 flex snap-x snap-mandatory gap-2.5 overflow-x-auto px-4 pb-1 [scrollbar-width:none] md:mx-0 md:grid md:grid-cols-3 md:px-0">{exp.map(([title,text],i)=><article key={title} className="min-w-[76vw] snap-start rounded-xl border border-brand-border bg-white p-4 md:min-w-0 md:rounded-[1.4rem] md:p-5"><span className="text-[10px] font-semibold text-brand-gold">0{i+1}</span><h3 className="mt-3 text-lg font-semibold text-brand-forest sm:text-2xl">{title}</h3><p className="mt-1.5 text-xs leading-5 text-brand-muted sm:text-sm sm:leading-6">{text}</p></article>)}</div></Container></section>}

function PlaceAndVideo(){const[showPlayer,setShowPlayer]=useState(false);const thumbnail=`https://img.youtube.com/vi/${YOUTUBE_VIDEO_ID}/hqdefault.jpg`;return <section id="lugar" className="scroll-mt-24 bg-brand-warmWhite py-8 sm:py-12 lg:py-14"><Container><div className="grid gap-3 lg:grid-cols-2"><article className="flex flex-col rounded-[1.35rem] border border-brand-border bg-brand-cream p-5 sm:p-7"><Eyebrow>Lugar del campamento</Eyebrow><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em] text-brand-forest sm:text-4xl">Conocé la nueva ubicación.</h2><p className="mt-3 text-sm leading-6 text-brand-muted sm:text-base sm:leading-7">Abrí Google Maps para ver el punto exacto y calcular tu recorrido.</p><a href={MAPS_URL} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex min-h-10 items-center justify-center rounded-full bg-brand-forest px-5 text-xs font-semibold text-white sm:text-sm">Ver ubicación exacta →</a></article><article className="overflow-hidden rounded-[1.35rem] border border-brand-border bg-brand-forestDark text-white"><div className="p-5 pb-3 sm:p-7 sm:pb-4"><Eyebrow className="text-brand-gold">Sentí la experiencia</Eyebrow><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em] sm:text-4xl">Mirá lo que se vive en Gracia Camp.</h2></div><div className="aspect-video">{showPlayer?<iframe src={`https://www.youtube.com/embed/${YOUTUBE_VIDEO_ID}?autoplay=1`} title="Video Gracia Camp" className="h-full w-full" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/>:<button type="button" onClick={()=>setShowPlayer(true)} className="group relative h-full w-full"><Image src={thumbnail} alt="Video Gracia Camp" fill sizes="(min-width:1024px)50vw,100vw" className="object-cover opacity-70"/><span className="absolute inset-0 flex items-center justify-center"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-white text-lg text-brand-forest shadow-xl">▶</span></span></button>}</div></article></div></Container></section>}

function FAQ(){const items=[["¿Cómo me inscribo?","Completá el formulario de registro y seguí las indicaciones del equipo."],["¿Qué incluye?","La organización comunicará el detalle completo de lo incluido y recomendaciones antes del campamento."],["¿Dónde veo el reglamento?","Podés abrirlo desde el botón al final de esta página."]];return <section className="bg-brand-cream py-8 sm:py-12"><Container className="grid gap-5 lg:grid-cols-[.65fr_1.35fr]"><div><Eyebrow>Preguntas rápidas</Eyebrow><h2 className="mt-2 text-2xl font-semibold text-brand-forest sm:text-4xl">Antes de inscribirte.</h2></div><div className="grid gap-2">{items.map(([q,a])=><details key={q} className="group rounded-xl border border-brand-border bg-white px-4 py-3.5"><summary className="cursor-pointer list-none text-sm font-semibold text-brand-forest sm:text-base">{q}<span className="float-right text-brand-gold group-open:rotate-45">+</span></summary><p className="mt-3 pr-5 text-xs leading-5 text-brand-muted sm:text-sm sm:leading-6">{a}</p></details>)}</div></Container></section>}

function CTA(){return <section id="inscripcion" className="scroll-mt-24 bg-brand-forest py-9 text-white sm:py-14"><Container className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-gold">Tu lugar puede empezar acá</p><h2 className="mt-2 max-w-3xl text-2xl font-semibold leading-[1.04] sm:text-4xl lg:text-5xl">¿Listo para vivir Gracia Camp 2026?</h2><p className="mt-2 text-sm text-white/60">Completá tu inscripción y asegurá tu lugar.</p></div><div className="grid grid-cols-2 gap-2 lg:flex lg:flex-col"><ButtonLink href="/registro" variant="light" className="min-h-10 px-4 text-xs sm:text-sm">Inscribirme</ButtonLink><ButtonLink href="/reglamento" variant="secondary" className="min-h-10 border-white/25 px-4 text-xs text-white sm:text-sm">Reglamento</ButtonLink></div></Container></section>}

function Footer(){return <footer className="bg-brand-forestDark py-6 text-white"><Container className="flex flex-col gap-2 text-xs text-white/50 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-white">Ministerio de Jóvenes CBG</p><p className="mt-1">Gracia Camp 2026</p></div><p>© 2026 Ministerio de Jóvenes CBG.</p></Container></footer>}
function StickyMobileActions(){return <div className="fixed inset-x-0 bottom-0 z-40 border-t border-brand-border bg-brand-warmWhite/95 p-2 backdrop-blur md:hidden"><div className="grid grid-cols-[auto_1fr] items-center gap-2"><div className="px-2"><p className="text-[8px] uppercase tracking-wider text-brand-muted">Por persona</p><p className="text-sm font-semibold text-brand-forest">Gs. 400.000</p></div><Link href="/registro" className="flex min-h-10 items-center justify-center rounded-full bg-brand-forest px-4 text-xs font-semibold text-white">Inscribirme</Link></div></div>}

export default function CampamentoPage(){return <div className="min-h-screen bg-brand-warmWhite pb-14 text-brand-ink antialiased md:pb-0"><Header/><main><QuickNav/><InfoSection/><PreacherSection/><MerchSectionPublic/><PlaceAndVideo/><FAQ/><CTA/></main><Footer/><StickyMobileActions/></div>}
