"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

import Header from "@/components/Header";
import PreacherSection from "@/components/PreacherSection";
import MerchSectionPublic from "@/components/MerchSectionPublic";
import { ButtonLink, Container, Eyebrow } from "@/components/ui/design";

const MAPS_URL = "https://maps.app.goo.gl/bVdDJtbaZFsJN7Eo7";
const YOUTUBE_VIDEO_ID = "_EpTnktKT-o";
const CAMP_PRICE = 400000;
const formatPrice=(value:number)=>`Gs. ${value.toLocaleString("es-PY")}`;

function QuickNav(){return <div className="hidden sticky top-[68px] z-30 border-y border-brand-border bg-brand-warmWhite/95 backdrop-blur md:block"><Container className="flex gap-2 overflow-x-auto py-2 text-sm [scrollbar-width:none]">{[["Información","#info"],["Predicador","#predicador"],["Merch","#remera"],["Lugar + Video","#lugar"],["Inscripción","#inscripcion"]].map(([label,href])=><a key={href} href={href} className="whitespace-nowrap rounded-full border border-brand-border bg-white px-4 py-2 font-semibold text-brand-forest">{label}</a>)}</Container></div>}

function InfoSection(){const facts=[["Fecha","03 al 06 de diciembre"],["Precio",formatPrice(CAMP_PRICE)],["Lugar","Rancho Alegre · San Bernardino"],["Cupos","Limitados"]];return <section id="info" className="hidden scroll-mt-24 bg-brand-cream py-12 md:block lg:py-14"><Container><div className="max-w-3xl"><Eyebrow>Información clave</Eyebrow><h2 className="mt-2 text-4xl font-semibold leading-[1.05] tracking-[-.035em] text-brand-forest lg:text-5xl">Lo esencial de Gracia Camp.</h2><p className="mt-3 max-w-xl text-base leading-6 text-brand-muted">Todo lo importante, sin vueltas.</p></div><div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{facts.map(([label,value])=><div key={label} className="rounded-2xl border border-brand-border bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-brand-gold">{label}</p><p className="mt-2 text-lg font-semibold leading-tight text-brand-forest">{value}</p>{label==="Lugar"?<a href={MAPS_URL} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex text-xs font-semibold text-brand-forest underline underline-offset-4">Abrir Maps</a>:null}</div>)}</div><div className="mt-5 grid grid-cols-3 gap-3">{[["Palabra","Escuchar, preguntar y llevar la fe a la vida real."],["Comunidad","Amistades y conversaciones que se viven juntos."],["Aventura","Salir de la rutina y crear recuerdos con propósito."]].map(([title,text],i)=><article key={title} className="rounded-[1.4rem] border border-brand-border bg-white p-5"><span className="text-[10px] font-semibold text-brand-gold">0{i+1}</span><h3 className="mt-3 text-2xl font-semibold text-brand-forest">{title}</h3><p className="mt-2 text-sm leading-6 text-brand-muted">{text}</p></article>)}</div></Container></section>}

function PlaceAndVideo(){const[showPlayer,setShowPlayer]=useState(false);const thumbnail=`https://img.youtube.com/vi/${YOUTUBE_VIDEO_ID}/hqdefault.jpg`;return <section id="lugar" className="scroll-mt-24 bg-brand-warmWhite py-9 sm:py-12 lg:py-14"><Container><div className="grid gap-4 lg:grid-cols-2"><article className="flex flex-col rounded-[1.4rem] bg-brand-cream p-5 sm:border sm:border-brand-border sm:p-7"><Eyebrow>Lugar</Eyebrow><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em] text-brand-forest sm:text-4xl">Rancho Alegre · San Bernardino</h2><p className="mt-3 text-sm leading-6 text-brand-muted sm:text-base sm:leading-7">Abrí Google Maps para ver el punto exacto y calcular tu recorrido.</p><a href={MAPS_URL} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex min-h-11 items-center justify-center rounded-full bg-brand-forest px-5 text-xs font-semibold text-white sm:text-sm">Ver ubicación →</a></article><article className="overflow-hidden rounded-[1.4rem] bg-brand-forestDark text-white sm:border sm:border-brand-border"><div className="p-5 pb-3 sm:p-7 sm:pb-4"><Eyebrow className="text-brand-gold">Video</Eyebrow><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em] sm:text-4xl">Así se vive Gracia Camp.</h2></div><div className="aspect-video">{showPlayer?<iframe src={`https://www.youtube.com/embed/${YOUTUBE_VIDEO_ID}?autoplay=1`} title="Video Gracia Camp" className="h-full w-full" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/>:<button type="button" onClick={()=>setShowPlayer(true)} className="group relative h-full w-full"><Image src={thumbnail} alt="Video Gracia Camp" fill sizes="(min-width:1024px)50vw,100vw" className="object-cover opacity-70"/><span className="absolute inset-0 flex items-center justify-center"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-white text-lg text-brand-forest shadow-xl">▶</span></span></button>}</div></article></div></Container></section>}

function FAQ(){const items=[["¿Cómo me inscribo?","Completá el formulario de registro y seguí las indicaciones del equipo."],["¿Qué incluye?","La organización comunicará el detalle completo de lo incluido y recomendaciones antes del campamento."],["¿Dónde veo el reglamento?","Podés abrirlo desde el botón al final de esta página."]];return <section className="bg-brand-cream py-9 sm:py-12"><Container className="grid gap-5 lg:grid-cols-[.65fr_1.35fr]"><div><Eyebrow>Preguntas rápidas</Eyebrow><h2 className="mt-2 text-2xl font-semibold text-brand-forest sm:text-4xl">Antes de inscribirte.</h2></div><div className="grid gap-2">{items.map(([q,a])=><details key={q} className="group border-b border-brand-border py-3.5 md:rounded-xl md:border md:bg-white md:px-4"><summary className="cursor-pointer list-none text-sm font-semibold text-brand-forest sm:text-base">{q}<span className="float-right text-brand-gold group-open:rotate-45">+</span></summary><p className="mt-3 pr-5 text-xs leading-5 text-brand-muted sm:text-sm sm:leading-6">{a}</p></details>)}</div></Container></section>}

function CTA(){return <section id="inscripcion" className="scroll-mt-24 bg-brand-forest py-10 text-white sm:py-14"><Container className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-brand-gold">Tu lugar puede empezar acá</p><h2 className="mt-2 max-w-3xl text-2xl font-semibold leading-[1.04] sm:text-4xl lg:text-5xl">¿Listo para vivir Gracia Camp 2026?</h2></div><div className="grid grid-cols-2 gap-2 lg:flex lg:flex-col"><ButtonLink href="/registro" variant="light" className="min-h-10 px-4 text-xs sm:text-sm">Inscribirme</ButtonLink><ButtonLink href="/reglamento" variant="secondary" className="min-h-10 border-white/25 px-4 text-xs text-white sm:text-sm">Reglamento</ButtonLink></div></Container></section>}

function Footer(){return <footer className="bg-brand-forestDark py-6 text-white"><Container className="flex flex-col gap-2 text-xs text-white/50 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-white">Ministerio de Jóvenes CBG</p><p className="mt-1">Gracia Camp 2026</p></div><p>© 2026 Ministerio de Jóvenes CBG.</p></Container></footer>}
function StickyMobileActions(){return <div className="fixed inset-x-0 bottom-0 z-40 border-t border-brand-border bg-brand-warmWhite/95 p-2.5 backdrop-blur md:hidden"><Link href="/registro" className="flex min-h-11 items-center justify-center rounded-full bg-brand-forest px-4 text-sm font-semibold text-white">Inscribirme</Link></div>}

export default function CampamentoPage(){return <div className="min-h-screen bg-brand-warmWhite pb-16 text-brand-ink antialiased md:pb-0"><Header/><main><QuickNav/><InfoSection/><PreacherSection/><MerchSectionPublic/><PlaceAndVideo/><FAQ/><CTA/></main><Footer/><StickyMobileActions/></div>}
