"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent, type ReactNode } from "react";
import Header from "@/components/Header";

type FormData = {
  nombre:string; apellido:string; edad:string; telefono:string; cedula:string; sexo:string;
  iglesia:string; esInvitado:string; invitadoPor:string; alergias:string; medicamentos:string;
  enfermedadBase:string; contactoEmergenciaNombre:string; contactoEmergenciaTelefono:string;
  formaPago:string; nombrePadreMadre:string; telefonoPadreMadre:string;
  deseaRemera:string; talleRemera:string; colorRemera:string; deseaGorra:string; colorGorra:string;
};
type PaymentSettings = { bankName:string; accountHolder:string; accountNumber:string; documentNumber:string };
type AcceptanceSettings={acceptanceEyebrow:string;acceptanceHeading:string;acceptanceIntro:string;acceptanceLabel:string;acceptanceText:string;acceptanceNote:string;guardianAcceptanceLabel:string;guardianAcceptanceText:string};

const CAMP_PRICE=450000;
const initialForm:FormData={nombre:"",apellido:"",edad:"",telefono:"",cedula:"",sexo:"",iglesia:"",esInvitado:"",invitadoPor:"",alergias:"",medicamentos:"",enfermedadBase:"",contactoEmergenciaNombre:"",contactoEmergenciaTelefono:"",formaPago:"transferencia",nombrePadreMadre:"",telefonoPadreMadre:"",deseaRemera:"no",talleRemera:"",colorRemera:"",deseaGorra:"no",colorGorra:""};
const emptyPayment:PaymentSettings={bankName:"",accountHolder:"",accountNumber:"",documentNumber:""};
const defaultAcceptance:AcceptanceSettings={acceptanceEyebrow:"Obligatorio para finalizar",acceptanceHeading:"Normas y convivencia del campamento",acceptanceIntro:"Antes de enviar tu inscripción, confirmá que conocés y aceptás las condiciones de participación de Gracia Camp.",acceptanceLabel:"Compromiso del participante",acceptanceText:"Declaro que leí, comprendí y me comprometo a respetar el reglamento, las normas de convivencia, las indicaciones de los líderes y las políticas generales de Gracia Camp durante toda la actividad.",acceptanceNote:"El incumplimiento de las normas podrá implicar medidas disciplinarias o la exclusión de actividades, según corresponda.",guardianAcceptanceLabel:"Autorización del padre, madre o tutor",guardianAcceptanceText:"Como responsable del menor, autorizo su participación y declaro conocer y aceptar el reglamento, las normas y las condiciones generales del campamento."};
const DRAFT_KEY="gracia-camp-registro-draft";
const formatGs=(value:number)=>`Gs. ${value.toLocaleString("es-PY")}`;

export default function RegistroPage(){
  const router=useRouter();
  const[formData,setFormData]=useState<FormData>(initialForm);
  const[paymentProof,setPaymentProof]=useState<File|null>(null);
  const[payment,setPayment]=useState<PaymentSettings>(emptyPayment);
  const[acceptance,setAcceptance]=useState<AcceptanceSettings>(defaultAcceptance);
  const[submitError,setSubmitError]=useState("");
  const[isSubmitting,setIsSubmitting]=useState(false);
  const[aceptaReglamento,setAceptaReglamento]=useState(false);
  const[autorizaResponsable,setAutorizaResponsable]=useState(false);

  useEffect(()=>{try{const saved=sessionStorage.getItem(DRAFT_KEY);if(saved)setFormData({...initialForm,...JSON.parse(saved),formaPago:"transferencia",deseaRemera:"no",talleRemera:"",colorRemera:"",deseaGorra:"no",colorGorra:""});}catch{}},[]);
  useEffect(()=>{try{sessionStorage.setItem(DRAFT_KEY,JSON.stringify(formData));}catch{}},[formData]);
  useEffect(()=>{fetch("/api/payment-settings",{cache:"no-store"}).then(r=>r.ok?r.json():emptyPayment).then(setPayment).catch(()=>setPayment(emptyPayment));},[]);
  useEffect(()=>{fetch("/api/registration-settings",{cache:"no-store"}).then(r=>r.ok?r.json():defaultAcceptance).then(data=>setAcceptance({...defaultAcceptance,...data})).catch(()=>setAcceptance(defaultAcceptance));},[]);

  const esMenor=useMemo(()=>formData.edad!==""&&Number(formData.edad)<18,[formData.edad]);
  const paymentReady=Boolean(payment.bankName&&payment.accountHolder&&payment.accountNumber);

  function handleChange(event:ChangeEvent<HTMLInputElement|HTMLSelectElement>){const{name,value}=event.target;setFormData(current=>({...current,[name]:value}));setSubmitError("");}

  async function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!aceptaReglamento){setSubmitError("Para completar la inscripción tenés que aceptar el reglamento, las normas de convivencia y las políticas del campamento.");return;}if(esMenor&&!autorizaResponsable){setSubmitError("El padre, madre o tutor debe autorizar la participación del menor y aceptar las normas del campamento.");return;}if(isSubmitting)return;setIsSubmitting(true);setSubmitError("");try{const body=new FormData();Object.entries({...formData,deseaRemera:"no",talleRemera:"",colorRemera:"",deseaGorra:"no",colorGorra:""}).forEach(([key,value])=>body.append(key,value));if(paymentProof)body.append("paymentProof",paymentProof);body.append("aceptaReglamento","si");body.append("aceptacionFecha",new Date().toISOString());if(esMenor)body.append("autorizaResponsable","si");const response=await fetch("/api/registro",{method:"POST",body});const result=await response.json().catch(()=>({}));if(!response.ok){setSubmitError(result.error??"No se pudo guardar tu inscripción.");return;}try{sessionStorage.removeItem(DRAFT_KEY);}catch{}router.push("/reglamento");}catch{setSubmitError("No se pudo conectar con el servidor. Intentá nuevamente.");}finally{setIsSubmitting(false);}}

  return <div className="min-h-screen bg-brand-warmWhite text-brand-ink"><Header/>
    <section className="bg-brand-cream py-14 sm:py-20"><div className="mx-auto max-w-5xl px-5"><p className="text-sm font-medium tracking-[.18em] text-brand-gold">Club de Jóvenes CBG</p><h1 className="mt-4 text-4xl font-semibold text-brand-forest sm:text-6xl">Registro Campamento 2026</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-brand-muted">Completá tus datos y confirmá tu inscripción con la transferencia.</p><div className="mt-5 inline-flex items-center gap-3 rounded-full border border-brand-border bg-white px-5 py-3"><span className="text-sm text-brand-muted">Valor del campamento</span><strong className="text-lg text-brand-forest">{formatGs(CAMP_PRICE)}</strong></div></div></section>
    <form onSubmit={handleSubmit} className="mx-auto max-w-5xl space-y-4 px-5 py-12">
      <AccordionSection number="01" title="Datos personales" defaultOpen><div className="space-y-6"><div className="grid gap-5 md:grid-cols-2"><Field label="Nombre" name="nombre" value={formData.nombre} onChange={handleChange}/><Field label="Apellido" name="apellido" value={formData.apellido} onChange={handleChange}/><Field label="Edad" name="edad" value={formData.edad} onChange={handleChange} type="number"/><Field label="Número de teléfono" name="telefono" value={formData.telefono} onChange={handleChange}/><Field label="Cédula" name="cedula" value={formData.cedula} onChange={handleChange}/><Select label="Sexo" name="sexo" value={formData.sexo} onChange={handleChange} options={[["","Seleccionar"],["masculino","Masculino"],["femenino","Femenino"]]}/></div></div></AccordionSection>
      <AccordionSection number="02" title="Información adicional"><div className="grid gap-5 md:grid-cols-2"><Field label="Iglesia / congregación" name="iglesia" value={formData.iglesia} onChange={handleChange} required={false}/><Select label="¿Sos invitado?" name="esInvitado" value={formData.esInvitado} onChange={handleChange} options={[["","Seleccionar"],["no","No"],["si","Sí"]]}/>{formData.esInvitado==="si"?<Field label="Nombre de quien te invitó" name="invitadoPor" value={formData.invitadoPor} onChange={handleChange}/>:null}</div></AccordionSection>
      {esMenor?<AccordionSection number="03" title="Responsable"><div className="grid gap-5 md:grid-cols-2"><Field label="Nombre del padre, madre o tutor" name="nombrePadreMadre" value={formData.nombrePadreMadre} onChange={handleChange}/><Field label="Teléfono del responsable" name="telefonoPadreMadre" value={formData.telefonoPadreMadre} onChange={handleChange}/></div></AccordionSection>:null}
      <AccordionSection number="04" title="Salud"><div className="grid gap-5 md:grid-cols-2"><Field label="¿Tiene alguna alergia?" name="alergias" value={formData.alergias} onChange={handleChange} required={false}/><Field label="¿Qué medicamento toma?" name="medicamentos" value={formData.medicamentos} onChange={handleChange} required={false}/><Field label="¿Tiene enfermedad de base?" name="enfermedadBase" value={formData.enfermedadBase} onChange={handleChange} required={false}/></div></AccordionSection>
      <AccordionSection number="05" title="Emergencia"><div className="grid gap-5 md:grid-cols-2"><Field label="Contacto de emergencia" name="contactoEmergenciaNombre" value={formData.contactoEmergenciaNombre} onChange={handleChange} required={false}/><Field label="Teléfono de emergencia" name="contactoEmergenciaTelefono" value={formData.contactoEmergenciaTelefono} onChange={handleChange} required={false}/></div></AccordionSection>
      <AccordionSection number="06" title="Pago"><section className="rounded-2xl border border-brand-border bg-white p-5 sm:p-7"><div className="flex flex-col gap-2 border-b border-brand-border pb-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand-gold">Transferencia bancaria</p><h3 className="text-xl font-semibold text-brand-forest">Revisá el total antes de transferir</h3><p className="text-sm text-brand-muted">Podés completar tu inscripción aunque todavía no adjuntes el comprobante.</p></div><div className="my-5 rounded-2xl bg-brand-cream p-5"><PriceRow label="Campamento" value={CAMP_PRICE}/><div className="flex items-end justify-between gap-4 pt-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand-gold">Total a transferir</p><p className="mt-1 text-xs text-brand-muted">Este es el monto total de tu inscripción.</p></div><strong className="text-2xl text-brand-forest sm:text-3xl">{formatGs(CAMP_PRICE)}</strong></div></div>{paymentReady?<div className="divide-y divide-brand-border"><PaymentRow label="Banco" value={payment.bankName}/><PaymentRow label="Titular" value={payment.accountHolder}/><PaymentRow label="Cuenta / Alias" value={payment.accountNumber}/>{payment.documentNumber?<PaymentRow label="CI / RUC" value={payment.documentNumber}/>:null}</div>:<div className="py-5 text-sm text-brand-muted">Los datos bancarios todavía no fueron configurados por administración.</div>}<div className="border-t border-brand-border pt-5"><label className="block"><span className="text-sm font-semibold text-brand-forest">Adjuntar comprobante <span className="font-normal text-brand-muted">(opcional)</span></span><span className="mt-1 block text-xs text-brand-muted">Podés adjuntarlo ahora para facilitar la verificación del pago.</span><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>{setPaymentProof(e.target.files?.[0]??null);setSubmitError("");}} className="mt-4 block w-full rounded-xl border border-brand-border bg-white p-3 text-sm"/></label>{paymentProof?<p className="mt-3 text-sm font-medium text-brand-forest">✓ {paymentProof.name}</p>:null}</div></section></AccordionSection>
      <AccordionSection number="07" title="Aceptación"><section className="rounded-2xl border border-brand-border bg-white p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand-gold">{acceptance.acceptanceEyebrow}</p><h3 className="mt-2 text-xl font-semibold text-brand-forest">{acceptance.acceptanceHeading}</h3><p className="mt-3 text-sm leading-6 text-brand-muted">{acceptance.acceptanceIntro}</p><label className="mt-5 flex gap-3"><input type="checkbox" checked={aceptaReglamento} onChange={e=>setAceptaReglamento(e.target.checked)} className="mt-1 h-4 w-4"/><span><strong className="block text-sm text-brand-forest">{acceptance.acceptanceLabel}</strong><span className="mt-1 block text-sm leading-6 text-brand-muted">{acceptance.acceptanceText}</span></span></label>{esMenor?<label className="mt-5 flex gap-3"><input type="checkbox" checked={autorizaResponsable} onChange={e=>setAutorizaResponsable(e.target.checked)} className="mt-1 h-4 w-4"/><span><strong className="block text-sm text-brand-forest">{acceptance.guardianAcceptanceLabel}</strong><span className="mt-1 block text-sm leading-6 text-brand-muted">{acceptance.guardianAcceptanceText}</span></span></label>:null}<p className="mt-4 text-xs leading-5 text-brand-muted">{acceptance.acceptanceNote}</p></section></AccordionSection>
      {submitError?<p className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{submitError}</p>:null}
      <div className="flex justify-end"><button type="submit" disabled={isSubmitting} className="rounded-full bg-brand-forest px-7 py-3 text-sm font-semibold text-white disabled:opacity-60">{isSubmitting?"Enviando...":"Completar inscripción"}</button></div>
    </form>
  </div>;
}

function AccordionSection({number,title,children,defaultOpen=false}:{number:string;title:string;children:ReactNode;defaultOpen?:boolean}){return <details open={defaultOpen} className="overflow-hidden rounded-2xl border border-brand-border bg-white"><summary className="cursor-pointer list-none px-5 py-4 sm:px-6"><div className="flex items-center gap-3"><span className="text-xs font-semibold text-brand-gold">{number}</span><span className="font-semibold text-brand-forest">{title}</span></div></summary><div className="border-t border-brand-border p-5 sm:p-6">{children}</div></details>}
function Field({label,name,value,onChange,type="text",required=true}:{label:string;name:string;value:string;onChange:(e:ChangeEvent<HTMLInputElement>)=>void;type?:string;required?:boolean}){return <label className="block"><span className="mb-2 block text-sm font-semibold text-brand-forest">{label}{required?" *":""}</span><input name={name} value={value} onChange={onChange} type={type} required={required} className="h-13 w-full rounded-xl border border-brand-border bg-white px-4 py-3 outline-none focus:border-brand-forest"/></label>}
function Select({label,name,value,onChange,options}:{label:string;name:string;value:string;onChange:(e:ChangeEvent<HTMLSelectElement>)=>void;options:[string,string][]}){return <label className="block"><span className="mb-2 block text-sm font-semibold text-brand-forest">{label} *</span><select name={name} value={value} onChange={onChange} required className="h-13 w-full rounded-xl border border-brand-border bg-white px-4 py-3 outline-none focus:border-brand-forest">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function PriceRow({label,value}:{label:string;value:number}){return <div className="flex items-center justify-between gap-4 border-b border-brand-border pb-4"><span className="text-sm text-brand-muted">{label}</span><strong className="text-brand-forest">{formatGs(value)}</strong></div>}
function PaymentRow({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between gap-4 py-3"><span className="text-sm text-brand-muted">{label}</span><strong className="text-right text-sm text-brand-forest">{value}</strong></div>}
